import {setup,unlock,decryptPayload,kid,unlockJwk,importPriv,wrapWith,unwrapWith,rand,b64,ub64} from './crypto.js?v=3';
const $=s=>document.querySelector(s),root=$('#root');
const inr=n=>{const v=Number(n);return isFinite(v)?(v<0?'-':'')+'₹'+Math.round(Math.abs(v)).toLocaleString('en-IN'):'—'};
const A=x=>Array.isArray(x)&&x.length?x:null;const pct=(a,b)=>b?Math.round((a-b)/b*100):null;const arrow=p=>p===null?'':p===0?'0%':(p>0?'▲ ':'▼ ')+Math.abs(p)+'%';const ageTxt=h=>h<24?Math.round(h)+'h':Math.floor(h/24)+'d '+Math.round(h%24)+'h';const none=m=>`<div class="glass empty">${m}</div>`;
const bc=x=>x?(Array.isArray(x.bills)?x.bills.length:Number(x.bills||0)):0;const bl=x=>x?(A(x.billList)||(Array.isArray(x.bills)?A(x.bills):null)):null;const SV=t=>`<i class="sv">${t}</i>`;const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const LS=localStorage;let hs=7,detail=null,bs='today',priv=null,myKid=null,data=null,tab='today',q='',ch='All',status='',sv='online',rq='',rf='All';const pmOn=()=>LS.getItem('dj_pm')==='1';
const shell=inner=>`<div class="app"><div class="blob b1"></div><div class="blob b2"></div><div class="blob b3"></div>${inner}</div>`;
const logo='<img class="logo" src="icon-192.png" alt="Dressjet">';
const DEV=()=>JSON.parse(LS.getItem('dj_dev')||'null');
async function devKey(d,assert){const o={publicKey:{challenge:rand(32),rpId:location.hostname,allowCredentials:[{type:'public-key',id:ub64(d.cred),transports:['internal']}],userVerification:'required',timeout:60000}};
 if(d.mode==='prf')o.publicKey.extensions={prf:{eval:{first:ub64(d.salt)}}};
 const r=await navigator.credentials.get(o);if(!(new Uint8Array(r.response.authenticatorData)[32]&4))throw new Error('Not confirmed.');
 if(d.mode==='prf'){const p=r.getClientExtensionResults().prf;if(!p||!p.results||!p.results.first)throw new Error('Phone did not return its key.');
  const h=await crypto.subtle.importKey('raw',p.results.first,'HKDF',false,['deriveBits']);return new Uint8Array(await crypto.subtle.deriveBits({name:'HKDF',hash:'SHA-256',salt:new Uint8Array(0),info:new TextEncoder().encode('djops-dev')},h,256));}
 return ub64(d.k);}
async function devEnable(jwkText){if(!window.PublicKeyCredential||!navigator.credentials)throw new Error('Not available on this phone.');
 if(PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable&&!(await PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable()))throw new Error('This phone has no screen lock available for the app.');
 const c=await navigator.credentials.create({publicKey:{rp:{name:'Dressjet Ops',id:location.hostname},user:{id:rand(16),name:'owner',displayName:'Owner'},challenge:rand(32),pubKeyCredParams:[{type:'public-key',alg:-7},{type:'public-key',alg:-257}],authenticatorSelection:{authenticatorAttachment:'platform',userVerification:'required',residentKey:'discouraged'},extensions:{prf:{}},timeout:60000,attestation:'none'}});
 const cred=b64(c.rawId),salt=b64(rand(32));let d={cred,mode:'gate',salt};
 const prf=c.getClientExtensionResults().prf;
 if(prf&&prf.enabled!==false&&prf.enabled!==undefined){try{d.mode='prf';const k=await devKey(d);d.w=await wrapWith(k,jwkText);}catch{d={cred,mode:'gate',salt};}}
 if(d.mode==='gate'){const k=rand(32);d.k=b64(k);d.w=await wrapWith(k,jwkText);const t=await devKey(d);void t;}
 LS.setItem('dj_dev',JSON.stringify(d));if(!LS.getItem('dj_cred')){LS.setItem('dj_cred',cred);LS.setItem('dj_lock','webauthn');}return d.mode;}
async function devUnlock(){const d=DEV(),k=await devKey(d);priv=await importPriv(await unwrapWith(k,d.w));}
function offerDev(jwk){root.innerHTML=shell(`<div class="lock">${logo}<h1>Open with your phone lock?</h1><p>Use Face ID, fingerprint or your phone passcode to open the app next time instead of typing the passphrase. The passphrase stays as a backup.</p><div class="glass"><button class="btn" id="dvy">Turn on phone unlock</button><button class="btn alt" id="dvn">Not now</button><div class="err" id="err"></div></div></div>`);
 $('#dvn').onclick=()=>{LS.setItem('dj_devno','1');start();};
 $('#dvy').onclick=async()=>{const e=$('#err');e.textContent='';$('#dvy').disabled=true;try{await devEnable(jwk);start();}catch(x){$('#dvy').disabled=false;e.textContent=(x&&x.name==='NotAllowedError'?'Cancelled. ':'')+(x&&x.name!=='NotAllowedError'?(x.message||'Could not turn on. '):'')+'You can try again from Settings.';setTimeout(start,1800);}};}
function lockScreen(auto){const v=JSON.parse(LS.getItem('dj_vault')||'null');const d=v&&DEV();
 const pass=`<p>Enter your passphrase to open.</p><div class="glass"><input id="pw" type="password" autocomplete="current-password" placeholder="Passphrase"><button class="btn" id="go">Unlock</button><div class="err" id="err"></div></div>`;
 root.innerHTML=shell(`<div class="lock">${logo}<h1>Dressjet Ops</h1>${d?`<p>Unlock with your phone lock.</p><div class="glass"><button class="btn" id="dvu">Unlock with phone</button><div class="err" id="err"></div></div><p class="note"><a href="#" id="upp" style="color:inherit">Use passphrase</a></p>`:v?pass:
 `<p>First time on this phone. Choose a passphrase. It never leaves this phone and cannot be recovered, so keep it somewhere safe.</p><div class="glass"><input id="pw" type="password" placeholder="Passphrase (10+ characters)"><input id="pw2" type="password" placeholder="Repeat passphrase"><button class="btn" id="go">Create</button><div class="err" id="err"></div></div>`}</div>`);
 if(d){const run=async()=>{const e=$('#err');e.textContent='';try{await devUnlock();myKid=await kid(v.pub);start();}catch(x){e.textContent=x&&x.name==='NotAllowedError'?'Cancelled. Tap to try again, or use the passphrase.':'Could not unlock with phone. Use the passphrase.';}};
  $('#dvu').onclick=run;$('#upp').onclick=ev=>{ev.preventDefault();const dd=DEV();LS.setItem('dj_dev_hold',JSON.stringify(dd));LS.removeItem('dj_dev');lockScreen();LS.setItem('dj_dev',LS.getItem('dj_dev_hold'));LS.removeItem('dj_dev_hold');};
  if(auto!==false)run();return;}
 $('#go').onclick=async()=>{const e=$('#err');e.textContent='';const pw=$('#pw').value;
  try{ if(v){priv=await unlock(v,pw);myKid=await kid(v.pub);
    if(!LS.getItem('dj_dev')&&!LS.getItem('dj_devno')&&window.PublicKeyCredential){offerDev(await unlockJwk(v,pw));}else start();}
   else{ if(pw.length<10){e.textContent='Use at least 10 characters.';return;} if(pw!==$('#pw2').value){e.textContent='Passphrases do not match.';return;}
    $('#go').textContent='Working...';const r=await setup(pw);LS.setItem('dj_vault',JSON.stringify(r.vault));showKey(r.pubText);} }
  catch(x){e.textContent=v?'Wrong passphrase.':'Something went wrong: '+x.message;$('#go').textContent=v?'Unlock':'Create';}};}
function showKey(t){root.innerHTML=shell(`<div class="lock">${logo}<h1>Almost done</h1><p>Send this public key to your assistant. It is not secret. It lets updates be locked so only this phone can read them.</p><div class="glass"><div class="keybox" id="k">${esc(t)}</div><button class="btn" id="cp">Copy key</button><button class="btn alt" id="sh">Share key</button><button class="btn alt" id="nx">Continue</button></div></div>`);
 $('#cp').onclick=async()=>{try{await navigator.clipboard.writeText(t);$('#cp').textContent='Copied'}catch{}};
 $('#sh').onclick=()=>navigator.share?navigator.share({text:t}):0;$('#nx').onclick=lockScreen;}
async function lastComment(repo,num){const h={Accept:'application/vnd.github+json'},iss=await (await fetch(`https://api.github.com/repos/${repo}/issues/${num}?_=${Date.now()}`,{cache:'no-store',headers:h})).json();const n=iss&&iss.comments;if(!n)throw new Error('No data yet');
 const r=await fetch(`https://api.github.com/repos/${repo}/issues/${num}/comments?per_page=1&page=${n}&_=${Date.now()}`,{cache:'no-store',headers:h});if(!r.ok)throw new Error('GitHub '+r.status);const j=await r.json();if(!j.length)throw new Error('No data yet');
 const own=String(repo).split('/')[0].toLowerCase();if(j[0].user&&String(j[0].user.login).toLowerCase()!==own)throw new Error('Newest comment is not from the owner');
 return j[0].body.trim().replace(/^```(json)?/,'').replace(/```$/,'').trim();}
async function fetchLatest(){const repo=(window.DJ_CONFIG||{}).repo;const body=await lastComment(repo,1);LS.setItem('dj_last',body);return body;}
async function loadStock(){const repo=(window.DJ_CONFIG||{}).repo;let b=null;
 try{b=await lastComment(repo,2);LS.setItem('dj_stk',b);}catch(e){b=LS.getItem('dj_stk');}
 if(!b)return;try{stk=await decryptPayload(JSON.parse(b),priv,myKid);applyStk();render();}catch(e){}}
async function load(){try{status='Updating...';render();let b;try{b=await fetchLatest();status='';}catch(e){b=LS.getItem('dj_last');status=b?'Offline, showing last saved data':'No data yet: '+e.message;if(!b){render();return;}}
 const dd=await decryptPayload(JSON.parse(b),priv,myKid);if(!dd||!dd.snapshot)throw new Error('unexpected payload');data=dd;applyStk();}catch(e){status='Could not read update: '+e.message;}render();loadStock();}

function detailTitle(){const i=detail.indexOf(':'),t=detail.slice(0,i),k=detail.slice(i+1);return t==='o'?'Order '+k:t==='c'?k:t==='s'?k:t==='r'?'Revenue today':t==='rb'?'Bill '+k.split('||')[1]:t==='set'?'Settings':t==='db'?'Bill '+k.split('|')[2]:t==='dy'?(k.split('|')[0]==='r'?'Retail · ':'Online · ')+new Date(k.split('|')[1]+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'}):k;}
function ocard(o){const items=o.items?o.items.map(i=>esc(i.sku)+(i.qty>1?' ×'+i.qty:'')).join(', '):esc(o.skus||'');const st=o.status||'';
 return `<article class="glass order" data-d="o:${esc(o.id)}"><div class="otop"><b>${esc(o.id)}</b><span class="st ${st.toLowerCase()}">${esc(st)}</span></div><div class="osku">${items}</div><div class="ometa"><span>${esc(o.ch)}${o.pay?' · '+esc(o.pay):''} · ${o.ageH!=null?ageTxt(o.ageH)+' old':esc(o.time||'')}</span><b>${o.amt?inr(o.amt):'—'}</b></div></article>`;}
function kv(a,b){return `<div class="line"><span>${a}</span><b>${b}</b></div>`;}
function detailView(orders,live,pend,s){const i=detail.indexOf(':'),t=detail.slice(0,i),k=detail.slice(i+1);
 if(t==='o'){const o=orders.find(x=>String(x.id)===k)||pend.find(x=>String(x.id)===k);if(!o)return none('Order not in the latest data.');
  const items=o.items?o.items:(o.skus?String(o.skus).split(',').map(z=>({sku:z.trim(),qty:1})):[]);const units=items.reduce((a,b)=>a+b.qty,0);
  return `<section class="glass list">${kv('Status',esc(o.status))}${kv('Channel',esc(o.ch))}${o.pay?kv('Payment',esc(o.pay)):''}${kv('Amount',o.amt?inr(o.amt):'—')}${kv(o.ageH!=null?'Age':'Placed',o.ageH!=null?ageTxt(o.ageH):'Today '+esc(o.time))}${kv('Units',units||'—')}</section><h2>Items</h2><section class="glass list">${items.map(z=>kv(SV(esc(z.sku)),'× '+z.qty)).join('')||'<div class="empty">No item detail.</div>'}</section>`;}
 if(t==='c'){const l=live.filter(o=>o.ch===k),tot=l.reduce((a,b)=>a+b.amt,0),sk={};l.forEach(o=>o.items.forEach(z=>sk[z.sku]=(sk[z.sku]||0)+z.qty));
  const top=Object.entries(sk).sort((a,b)=>b[1]-a[1]).slice(0,5),cod=l.filter(o=>/cod/i.test(o.pay)).length;
  const OI=ordInfo(s),CS=chanOf(s,OI),cvv=CS.full&&CS.m[k],cvr=cvv?nn(typeof cvv==='object'?(cvv.amt!=null?cvv.amt:cvv.rev):cvv):tot,cvn=cvv&&typeof cvv==='object'&&cvv.n!=null?nn(cvv.n):l.length;return `${OI.partial&&!cvv?'<p class="note" style="padding:0 0 8px;text-align:left">Based on the '+orders.length+' itemised orders. Today has more, so this channel may be higher.</p>':''}<section class="glass list">${kv('Revenue today',inr(cvr))}${kv('Orders',cvn)}${kv('Avg order',inr(Math.round(cvr/Math.max(1,cvn))))}${kv('COD orders'+(OI.partial?' (itemised)':''),cod)}</section>${top.length?'<h2>Top SKUs</h2><section class="glass list">'+top.map(z=>kv(SV(esc(z[0])),z[1]+' sold')).join('')+'</section>':''}<h2>${OI.partial?'Orders (latest itemised: '+l.length+')':'Orders'}</h2><section class="ol">${l.map(ocard).join('')}</section>`;}
 if(t==='s'){const l=live.filter(o=>o.items.some(z=>z.sku===k)),q=l.reduce((a,o)=>a+o.items.filter(z=>z.sku===k).reduce((x,z)=>x+z.qty,0),0),S=data.sellers||{},st=(A(data.stock)||[]).find(z=>z.sku===k);
  const per=['week','month','quarter'].map(p=>{const r=A(S[p]);const n=r?r.findIndex(z=>z.sku===k):-1;return n>=0?kv({week:'Week',month:'Month',quarter:'90 days'}[p],'#'+(n+1)+(r[n].rev?' · '+inr(r[n].rev):'')):''}).join('');
  return `<section class="glass list">${kv('Sold today',q+' units')}${kv('Orders today',l.length)}${st?kv('In stock',st.onHand):''}${per}</section>${l.length?'<h2>Orders today</h2><section class="ol">'+l.map(ocard).join('')+'</section>':''}`;}
 if(t==='r'){const OI=ordInfo(s),CH=chanOf(s,OI),cn={};live.forEach(o=>cn[o.ch]=(cn[o.ch]||0)+1);const by=Object.entries(CH.m).map(([c,v])=>[c,(v&&typeof v==='object')?{amt:nn(v.amt!=null?v.amt:v.rev),n:v.n!=null?v.n:(v.orders!=null?v.orders:cn[c])}:{amt:nn(v),n:(CH.full?null:cn[c])}]).sort((a,b)=>(a[0]==='Not itemised')-(b[0]==='Not itemised')||b[1].amt-a[1].amt),top=[...live].sort((a,b)=>b.amt-a.amt).slice(0,5);
  return `<section class="glass list">${kv('Revenue so far',inr(s.revenue))}${kv('Yesterday full day',inr(s.revenuePrev))}${kv('Order items',s.items)}${kv('Orders',ordN(ordInfo(s)))}</section><h2>By channel</h2><section class="glass list">${by.map(([c,v])=>`<div class="line" ${c==='Not itemised'?'':'data-d="c:'+esc(c)+'"'}><span>${esc(c)}</span><b>${inr(v.amt)}${v.n?' · '+v.n:''}</b></div>`).join('')}</section><h2>Top orders</h2><section class="ol">${top.map(ocard).join('')}</section>`;}

 if(t==='rt'){const R=data.retail,S=R&&A(R.stores),x=S&&S.find(z=>String(z.name||'Store')===k);if(!x)return none('Store not in the latest data.');const n=v=>Number(v||0),tot=S.reduce((q,z)=>q+n(z.sales),0),B=A(x.billList);
  return `<section class="glass list">${kv('Sales (incl. GST)',inr(n(x.sales)))}${kv('Bills',n(x.bills))}${kv('Units',n(x.units))}${kv('Avg bill',inr(Math.round(n(x.sales)/Math.max(1,n(x.bills)))))}${kv('Units per bill',n(x.bills)?(n(x.units)/n(x.bills)).toFixed(1):'0')}${n(x.returns)?kv('Returns',n(x.returns)):''}${kv('Share of retail',(tot?Math.round(n(x.sales)/tot*100):0)+'%')}${R.at?kv('Updated',esc(R.at)):''}</section>${B?'<h2>Bills</h2><section class="glass list">'+B.map(z=>`<div class="line" data-d="rb:${esc(x.name||'Store')}||${esc(z.no||'')}"><span>${SV(esc(z.customer||'Walk-in'))}<br><small>${esc(z.no||'Bill')}${z.time?' · '+esc(z.time):''}${z.units?' · '+z.units+' unit'+(z.units>1?'s':''):''}</small></span><b>${inr(n(z.amt))}</b></div>`).join('')+'</section>':'<p class="note" style="padding-bottom:6px">Bill-level detail is not in the latest data.</p>'}`;}

 if(t==='rb'){const [sn,bn]=k.split('||'),R=data.retail,S=R&&A(R.stores),x=S&&S.find(z=>String(z.name||'Store')===sn),b=x&&A(x.billList)&&x.billList.find(z=>String(z.no)===bn);if(!b)return none('Bill not in the latest data.');const n=v=>Number(v||0),I=A(b.items);
  return `<section class="glass list">${kv('Customer',esc(b.customer||'Walk-in'))}${kv('Store',esc(sn))}${kv('Bill no',esc(b.no))}${b.time?kv('Time',esc(b.time)):''}${kv('Units',n(b.units)||(I?I.reduce((q,z)=>q+n(z.qty),0):'—'))}${kv('Amount (incl. GST)',inr(n(b.amt)))}</section><h2>Items</h2><section class="glass list">${I?I.map(z=>kv(SV(esc(z.sku||z.name||'Item')+(z.name&&z.sku?'<br><small>'+esc(z.name)+'</small>':'')),(z.qty?'× '+n(z.qty)+' · ':'')+(z.amt!=null?inr(n(z.amt)):''))).join(''):'<div class="empty">No item detail.</div>'}</section>`;}

 if(t==='dy'){const [kind,day]=k.split('|'),n=v=>Number(v||0),iso=IST(),today=day===iso;let rev,cnt,cl,units,items=null,note='',chan=null;
  if(kind==='o'){const e=(A(data.history)||[]).find(z=>z.d===day);
   if(today){const OI=ordInfo(s);rev=n(s.revenue);cnt=OI.n;cl='Orders';units=n(s.items);const m={};live.forEach(o=>o.items.forEach(z=>{const r=(m[z.sku]=m[z.sku]||{sku:z.sku,qty:0});r.qty+=n(z.qty)}));items=Object.values(m);chan=Object.fromEntries(Object.entries(chanOf(s,OI).m).map(([k,v])=>[k,(v&&typeof v==='object')?nn(v.amt!=null?v.amt:v.rev):nn(v)]));}
   else if(e){rev=n(e.rev);cnt=n(e.orders);cl='Orders';const arr=Array.isArray(e.items)?A(e.items):null;items=arr||A(e.itemList);units=Array.isArray(e.items)?(items||[]).reduce((q,z)=>q+n(z.qty),0):n(e.items);chan=e.ch||null;}}
  else{const R=data.retail,S=R&&A(R.stores)||[],H=A(data.retailHistory)||[],e=H.find(z=>z.d===day),sf=rf==='All'?S:S.filter(z=>z.name===rf);
   if(today){rev=sf.reduce((q,z)=>q+n(z.sales),0);cnt=sf.reduce((q,z)=>q+n(z.bills),0);units=sf.reduce((q,z)=>q+n(z.units),0);cl='Bills';const m={};sf.forEach(z=>(A(z.billList)||[]).forEach(b=>(A(b.items)||[]).forEach(it=>{const r=(m[it.sku]=m[it.sku]||{sku:it.sku,name:it.name||'',qty:0,amt:0});r.qty+=n(it.qty);r.amt+=n(it.amt);if(it.name&&!r.name)r.name=it.name})));items=Object.keys(m).length?Object.values(m):null;}
   else if(e){const src=rf==='All'?e:(e.by&&e.by[rf])||{};rev=n(src.rev);cnt=bc(src);units=n(src.units);cl='Bills';items=A(src.items);if(rf!=='All'&&!items)note=' for '+rf;}}
  if(rev===undefined)return none('No data recorded for this day.');
  if(items)items=[...items].sort((a,b)=>n(b.qty)-n(a.qty));
  return `<section class="glass list">${kv('Revenue (incl. GST)',inr(rev))}${kv(cl,cnt)}${kv('Units',units)}${cnt?kv('Avg '+(kind==='o'?'order':'bill'),inr(Math.round(rev/Math.max(1,cnt)))):''}${kind==='r'&&rf!=='All'?kv('Store',esc(rf)):''}${today?kv('Status','Today, still in progress'):''}</section>${chan&&Object.keys(chan).length?'<h2>By channel</h2><section class="glass list">'+Object.entries(chan).sort((a,b)=>n(b[1])-n(a[1])).map(([c,v])=>kv(esc(c),inr(n(v)))).join('')+'</section>':''}${(()=>{const B=dayBills(kind,day);if(!B)return `<h2>${kind==='o'?'Orders':'Bills'}</h2><p class="note" style="padding-bottom:6px">${kind==='o'?'Order':'Bill'} list not available for this day${note}.</p>`;return `<h2>${kind==='o'?'Orders':'Bills'} (${B.length})</h2><section class="glass list">${B.slice(0,100).map(b=>`<div class="line" data-d="${b.order?'o:'+esc(b.no):'db:'+kind+'|'+day+'|'+esc(b.no)}"><span>${b.customer?SV(esc(b.customer))+'<br>':''}<small>${esc(b.no)}${b.store&&rf==='All'&&kind==='r'?' · '+esc(b.store):''}${b.ch?' · '+esc(b.ch):''}${b.units?' · '+n(b.units)+' unit'+(n(b.units)>1?'s':''):''}</small></span><b>${inr(n(b.amt))}</b></div>`).join('')}</section>`})()}<h2>Articles sold</h2>${items&&items.length?'<section class="glass list">'+items.slice(0,80).map(z=>kv(SV(esc(z.sku)+(z.name?'<br><small>'+esc(z.name)+'</small>':'')),'× '+n(z.qty)+(z.amt!=null?' · '+inr(n(z.amt)):''))).join('')+'</section>':`<p class="note" style="padding-bottom:6px">Item detail not available for this day${note}.</p>`}`;}

 if(t==='db'){const [kind,day,no]=k.split('|'),n=v=>Number(v||0),B=dayBills(kind,day),b=B&&B.find(z=>String(z.no)===no);if(!b)return none('Bill not in the latest data.');const I=A(b.items);
  return `<section class="glass list">${b.customer?kv('Customer',esc(b.customer)):''}${b.store?kv('Store',esc(b.store)):''}${kv(kind==='o'?'Order no':'Bill no',esc(b.no))}${kv('Date',esc(new Date(day+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'})))}${kv('Units',n(b.units)||(I?I.reduce((q,z)=>q+n(z.qty),0):'—'))}${kv('Amount (incl. GST)',inr(n(b.amt)))}</section><h2>Items</h2><section class="glass list">${I?I.map(z=>kv(SV(esc(z.sku||z.name||'Item')+(z.name&&z.sku?'<br><small>'+esc(z.name)+'</small>':'')),(z.qty?'× '+n(z.qty)+' · ':'')+(z.amt!=null?inr(n(z.amt)):''))).join(''):'<div class="empty">No item detail.</div>'}</section>`;}
 if(t==='p'){const key=k.toLowerCase().replace(/[^a-z]/g,'');const norm=x=>String(x||'').toLowerCase().replace(/[^a-z]/g,'');
  const all=[...pend.map(x=>({...x})),...live.filter(o=>!pend.some(p=>String(p.id)===String(o.id)))];
  let l=all.filter(o=>/pending|unverified|label|pack|created|processing/i.test(o.status||'')&&o.status!=='Complete');
  if(/verif/.test(key))l=l.filter(o=>/verif/i.test(o.status));else if(/pack/.test(key))l=l.filter(o=>/pack|processing|created/i.test(o.status));else if(/label/.test(key))l=l.filter(o=>/label/i.test(o.status));else if(/fail/.test(key))l=all.filter(o=>/fail/i.test(o.status));
  l.sort((a,b)=>(b.ageH||0)-(a.ageH||0));
  return `<p class="note" style="padding-bottom:6px">${(()=>{const tv=[...(s.alerts||[]),...(s.pipeline||[])].find(x=>x.k===k);return tv&&Number(tv.v)>l.length?'Showing '+l.length+' of '+tv.v:l.length+' order'+(l.length===1?'':'s')})()} from the latest data. The dashboard count can be larger, as we only hold today's orders and the oldest pending ones.</p><section class="ol">${l.length?l.map(ocard).join(''):none('Nothing matching in the latest data.')}</section>`;}
 return none('Nothing to show.');}

function histView(s){const H=A(data.history);if(!H)return '';const iso=IST();
 const OI=ordInfo(s);let d=[...H].sort((a,b)=>a.d<b.d?-1:1).filter(x=>x.d<iso);d.push({d:iso,rev:s.revenue,items:s.items,orders:OI.n,partial:true,ch:Object.fromEntries(Object.entries(chanOf(s,OI).m).map(([k,v])=>[k,(v&&typeof v==='object')?nn(v.amt!=null?v.amt:v.rev):nn(v)]))});
 const N=hs,full=d.filter(x=>!x.partial),W=calWin(full,iso,N),cur=W.cur,prev=W.prev,tod=d[d.length-1],sum=(a,k)=>a.reduce((t,x)=>t+(x[k]||0),0),cr=sum(cur,'rev'),pr=sum(prev,'rev');
 const cc=[...W.dates.map(z=>W.by[z]||{d:z,miss:true,rev:0}),tod],mx=Math.max(1,...cc.map(x=>x.rev)),bw=300/cc.length,fmt=x=>{const t=new Date(x+'T00:00:00');return t.toLocaleDateString('en-IN',{day:'numeric',month:'short'})};
 const bars=cc.map((x,i)=>{const hh=Math.max(2,x.rev/mx*92);return `<g data-d="dy:o|${x.d}"><rect x="${(i*bw+10).toFixed(1)}" y="0" width="${bw.toFixed(1)}" height="100" fill="transparent"/><rect x="${(i*bw+bw*.15+10).toFixed(1)}" y="${(100-hh).toFixed(1)}" width="${(bw*.7).toFixed(1)}" height="${hh.toFixed(1)}" rx="3" fill="url(#g)" opacity="${x.miss?.18:x.partial?.55:1}"/></g>`}).join('');
 const chs={};cur.forEach(x=>Object.entries(x.ch||{}).forEach(([k,v])=>{(chs[k]=chs[k]||{c:0,p:0}).c+=v}));prev.forEach(x=>Object.entries(x.ch||{}).forEach(([k,v])=>{(chs[k]=chs[k]||{c:0,p:0}).p+=v}));
 const chl=Object.entries(chs).filter(e=>e[0]!=='Not itemised').sort((a,b)=>b[1].c-a[1].c);const ch=prev.length&&cur.length?pct(cr/cur.length,pr/prev.length):null,dayDiff=prev.length&&cur.length&&prev.length!==cur.length;
 return `<h2>Revenue</h2><section class="glass list"><div class="pills" style="padding:4px 0 10px"><button data-h="7" class="${hs===7?'on':''}">7 days</button><button data-h="30" class="${hs===30?'on':''}">30 days</button></div>
 <div class="line" style="border:0"><span>${cur.length?(cur.length<N?'Last '+N+' days ('+cur.length+' with data)':'Last '+N+' full days'):'No full days yet'}</span><b>${inr(cr)}</b></div>
 <div class="line" style="border:0;padding-top:0"><span>${prev.length?'Previous '+N+' days'+(prev.length<N?' ('+prev.length+' with data)':''):'Previous period'}</span><b>${prev.length?inr(pr)+' <small>'+arrow(ch)+(dayDiff?' per day':'')+'</small>':'<small>no data yet</small>'}</b></div>
 <svg viewBox="0 0 320 118" style="width:100%;margin-top:6px"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#f1e2c0"/><stop offset="1" stop-color="#9c8358"/></linearGradient></defs><line x1="10" y1="100.5" x2="310" y2="100.5" stroke="rgba(231,211,168,.25)"/>${bars}<text x="10" y="114" font-size="9" fill="rgba(242,232,216,.55)">${fmt(cc[0].d)}</text><text x="310" y="114" font-size="9" text-anchor="end" fill="rgba(242,232,216,.55)">Today</text></svg>
 ${chl.length?'<div style="margin-top:8px">'+chl.map(([k,v])=>`<div class="line"><span>${esc(k)}</span><b>${inr(v.c)} <small>${v.p&&prev.length&&cur.length?arrow(pct(v.c/cur.length,v.p/prev.length)):''}</small></b></div>`).join('')+'</div>':''}</section><p class="note" style="padding-bottom:0">Totals use completed days. Today's bar (faded) is partial; missing days show as a faint stub. History starts from when tracking began.</p>`;}
function retailHist(S0){const H0=A(data.retailHistory);const n=v=>Number(v||0);const names=S0.map(x=>x.name).filter(Boolean);if(rf!=='All'&&!names.includes(rf))rf='All';
 const S=rf==='All'?S0:S0.filter(x=>x.name===rf),H=H0&&(rf==='All'?H0:H0.filter(x=>x.by&&x.by[rf]).map(x=>({d:x.d,...x.by[rf]})));
 const rs=S.reduce((t,x)=>t+n(x.sales),0),rb=S.reduce((t,x)=>t+n(x.bills),0),ru=S.reduce((t,x)=>t+n(x.units),0);
 const iso=IST();
 const d=[...(H||[])].sort((a,b)=>a.d<b.d?-1:1).filter(x=>x.d<iso);d.push({d:iso,rev:rs,bills:rb,units:ru,partial:true});
 const N=hs,full=d.filter(x=>!x.partial),W=calWin(full,iso,N),cur=W.cur,prev=W.prev,tod=d[d.length-1],sum=(a,k)=>a.reduce((t,x)=>t+n(x[k]),0),cr=sum(cur,'rev'),pr=sum(prev,'rev');
 const yd=W.by[addD(iso,-1)],cc=[...W.dates.map(z=>W.by[z]||{d:z,miss:true,rev:0}),tod],mx=Math.max(1,...cc.map(x=>n(x.rev))),bw=300/cc.length,fmt=x=>new Date(x+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'});
 const bars=cc.map((x,i)=>{const hh=Math.max(2,n(x.rev)/mx*92);return `<g data-d="dy:r|${x.d}"><rect x="${(i*bw+10).toFixed(1)}" y="0" width="${bw.toFixed(1)}" height="100" fill="transparent"/><rect x="${(i*bw+bw*.15+10).toFixed(1)}" y="${(100-hh).toFixed(1)}" width="${(bw*.7).toFixed(1)}" height="${hh.toFixed(1)}" rx="3" fill="url(#rg2)" opacity="${x.miss?.18:x.partial?.55:1}"/></g>`}).join('');
 const ch=prev.length&&cur.length?pct(cr/cur.length,pr/prev.length):null,dayDiff=prev.length&&cur.length&&prev.length!==cur.length,sparse=full.length<2*N;
 return `<h2>Revenue</h2>${names.length>1?`<div class="pills">${['All',...names].map(z=>`<button data-rf="${esc(z)}" class="${rf===z?'on':''}">${esc(z)}</button>`).join('')}</div>`:''}<section class="glass list"><div class="pills" style="padding:4px 0 10px"><button data-h="7" class="${hs===7?'on':''}">7 days</button><button data-h="30" class="${hs===30?'on':''}">30 days</button></div>
 <div class="line" style="border:0"><span>${cur.length?(cur.length<N?'Last '+N+' days ('+cur.length+' with data)':'Last '+N+' full days'):'No full days yet'}</span><b>${inr(cr)}</b></div>
 <div class="line" style="border:0;padding-top:0"><span>${prev.length?'Previous '+N+' days'+(prev.length<N?' ('+prev.length+' with data)':''):'Previous period'}</span><b>${prev.length?inr(pr)+' <small>'+arrow(ch)+(dayDiff?' per day':'')+'</small>':'<small>no data yet</small>'}</b></div>
 <div class="line" style="border:0;padding-top:0"><span>Today so far vs yesterday</span><b>${yd&&yd.rev!=null?inr(rs)+' <small>'+(n(yd.rev)?arrow(pct(rs,n(yd.rev)))+' of '+inr(n(yd.rev)):'')+'</small>':'<small>no data yet</small>'}</b></div>
 <svg viewBox="0 0 320 118" style="width:100%;margin-top:6px"><defs><linearGradient id="rg2" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#f1e2c0"/><stop offset="1" stop-color="#9c8358"/></linearGradient></defs><line x1="10" y1="100.5" x2="310" y2="100.5" stroke="rgba(231,211,168,.25)"/>${bars}<text x="10" y="114" font-size="9" fill="rgba(242,232,216,.55)">${fmt(cc[0].d)}</text><text x="310" y="114" font-size="9" text-anchor="end" fill="rgba(242,232,216,.55)">Today</text></svg>
 ${cur.length?`<div class="line"><span>Bills · units (period)</span><b>${cur.reduce((q,x)=>q+bc(x),0)} · ${sum(cur,'units')}</b></div>`:''}</section><p class="note" style="padding-bottom:0">${sparse?'Builds up as days are recorded. ':''}Totals use completed days. Today's bar (faded) is partial. Incl. GST.</p>`;}
function retailView(){const R=data.retail;const S=R&&A(R.stores);if(!S)return `<section class="glass list"><div class="line"><span>Waiting for retail data</span><b><small>Logic ERP stores</small></b></div></section>`;
 const n=x=>Number(x||0),sum=k=>S.reduce((t,x)=>t+n(x[k]),0);const sales=sum('sales'),bills=sum('bills'),units=sum('units'),ret=sum('returns');
 const H=A(R.hourly);let hb='';if(H){const mx=Math.max(1,...H.map(x=>n(x.sales)));const w=300/H.length;hb=`<section class="glass" style="padding:16px 18px"><span class="eyebrow">Sales by hour</span><svg viewBox="0 0 320 100" style="width:100%;margin-top:8px"><defs><linearGradient id="rg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#f1e2c0"/><stop offset="1" stop-color="#9c8358"/></linearGradient></defs><line x1="10" y1="80.5" x2="310" y2="80.5" stroke="rgba(231,211,168,.25)"/>${H.map((x,i)=>{const bh=Math.max(1,n(x.sales)/mx*70);return `<rect x="${(10+i*w+w*.15).toFixed(1)}" y="${(80-bh).toFixed(1)}" width="${(w*.7).toFixed(1)}" height="${bh.toFixed(1)}" rx="2" fill="url(#rg)"/>`}).join('')}<text x="10" y="94" font-size="9" fill="rgba(242,232,216,.55)">${esc(H[0].h)}</text><text x="310" y="94" font-size="9" text-anchor="end" fill="rgba(242,232,216,.55)">${esc(H[H.length-1].h)}</text></svg></section>`;}
 return `<section class="glass hero"><span class="eyebrow">Retail sales today · incl. GST</span><div class="big">${inr(sales)}</div><div class="sub"><span class="chip">so far</span> Updated ${esc(R.at||'')}</div><div class="split"><div><b>${bills}</b><span>bills</span></div><div><b>${units}</b><span>units</span></div><div><b>${inr(Math.round(sales/Math.max(1,bills)))}</b><span>avg bill</span></div></div></section>
 ${ret?`<div class="grid2"><div class="glass tile amber"><b>${ret}</b><span>Returns today</span></div><div class="glass tile"><b>${units?(bills?(units/bills).toFixed(1):'0'):'0'}</b><span>Units per bill</span></div></div>`:''}
 <h2>Stores</h2>${S.slice().sort((a,b)=>n(b.sales)-n(a.sales)).map(x=>`<section class="glass list" data-d="rt:${esc(x.name||'Store')}"><div class="line" style="border:0"><span><b style="font-family:var(--serif,inherit)">${esc(x.name||'Store')}</b></span><b>${inr(n(x.sales))}</b></div><div class="line" style="border:0;padding-top:0"><span>${SV(n(x.bills)+' bills · '+n(x.units)+' units')}</span><b><small>${n(x.returns)?n(x.returns)+(n(x.returns)===1?' return · ':' returns · '):''}${sales?Math.round(n(x.sales)/sales*100):0}% of retail</small></b></div></section>`).join('')}
 ${hb}${retailHist(S)}<p class="note">Retail (Logic ERP) is kept separate from online. Customer names appear only in bill details.</p>`;}
function retailStockView(){const RS=A(data.retailStock);if(!RS)return `<section class="glass list"><div class="line"><span>Waiting for retail stock</span><b><small>Logic ERP</small></b></div></section>`;
 const n=v=>Number(v||0),m={};RS.forEach(x=>{const k=String(x.sku);const r=(m[k]=m[k]||{sku:k,name:x.name||'',onHand:0,by:{}});r.onHand+=n(x.onHand);if(x.name&&!r.name)r.name=x.name;if(x.store)r.by[x.store]=(r.by[x.store]||0)+n(x.onHand);});
 const RT=data.retailStockTotal,trunc=RT&&Number(RT.skus)>Object.keys(m).length,all=Object.values(m),units=RT&&RT.units!=null?Number(RT.units):all.reduce((t,x)=>t+Math.max(0,x.onHand),0),skuN=RT&&RT.skus!=null?Number(RT.skus):all.length,oos=all.filter(x=>x.onHand<=0).length,low=all.filter(x=>x.onHand>0&&x.onHand<=3).length;
 const f=all.filter(x=>!rq||(x.sku+' '+x.name).toLowerCase().includes(rq.toLowerCase())).sort((a,b)=>a.onHand-b.onHand||a.sku.localeCompare(b.sku));
 const stores=[...new Set(RS.map(x=>x.store).filter(Boolean))];
 return `<div class="grid2"><div class="glass tile"><b>${units.toLocaleString('en-IN')}</b><span>Retail stock, all stores</span></div><div class="glass tile"><b>${skuN.toLocaleString('en-IN')}</b><span>SKUs</span></div></div><div class="grid2" style="margin-top:12px"><div class="glass tile ${oos?'amber':''}"><b>${oos}</b><span>Out of stock${trunc?' (in list)':''}</span></div><div class="glass tile ${low?'amber':''}"><b>${low}</b><span>Low, 3 or fewer${trunc?' (in list)':''}</span></div></div>
 <div class="glass search" style="margin-top:12px"><input id="rq" placeholder="Search SKU or name" value="${esc(rq)}"></div>
 <h2>Lowest stock first</h2><section class="glass list">${f.length?f.slice(0,100).map(x=>`<div class="line"><span>${SV(esc(x.sku)+(x.name?'<br><small>'+esc(x.name)+'</small>':''))}${stores.length>1?'<br><small>'+Object.entries(x.by).map(([s,v])=>esc(s)+' '+v).join(' · ')+'</small>':''}</span><b class="${x.onHand<=3?'low':''}">${x.onHand} in stock</b></div>`).join(''):'<div class="empty">No SKU matches.</div>'}</section><p class="note">Showing ${Math.min(100,f.length)} of ${f.length}${rq?' matching':''} SKUs${!rq&&skuN!==f.length?' ('+skuN.toLocaleString('en-IN')+' total)':''}. Retail (Logic ERP) stock, separate from online.${trunc?' The list holds only the '+all.length+' lowest-stock SKUs.':''}</p>`;}
async function pinHash(pin,salt){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(pin),'PBKDF2',false,['deriveBits']);const b=await crypto.subtle.deriveBits({name:'PBKDF2',salt:Uint8Array.from(atob(salt),c=>c.charCodeAt(0)),iterations:150000,hash:'SHA-256'},k,256);return btoa(String.fromCharCode(...new Uint8Array(b)))}
const lockKind=()=>LS.getItem('dj_lock')||(LS.getItem('dj_pin')?'pin':'');let pmUi='';
const u8=b=>Uint8Array.from(atob(b),c=>c.charCodeAt(0));
async function waRegister(){if(!window.PublicKeyCredential||!navigator.credentials)throw new Error('Phone unlock is not available in this app.');
 if(PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable&&!(await PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable()))throw new Error('This phone has no screen lock available for the app.');
 const c=await navigator.credentials.create({publicKey:{rp:{name:'Dressjet Ops',id:location.hostname},user:{id:crypto.getRandomValues(new Uint8Array(16)),name:'owner',displayName:'Owner'},challenge:crypto.getRandomValues(new Uint8Array(32)),pubKeyCredParams:[{type:'public-key',alg:-7},{type:'public-key',alg:-257}],authenticatorSelection:{authenticatorAttachment:'platform',userVerification:'required',residentKey:'discouraged'},timeout:60000,attestation:'none'}});
 LS.setItem('dj_cred',btoa(String.fromCharCode(...new Uint8Array(c.rawId))));LS.setItem('dj_lock','webauthn');}
async function waVerify(){const id=LS.getItem('dj_cred');if(!id)throw new Error('No phone unlock is registered.');
 const r=await navigator.credentials.get({publicKey:{challenge:crypto.getRandomValues(new Uint8Array(32)),rpId:location.hostname,allowCredentials:[{type:'public-key',id:u8(id),transports:['internal']}],userVerification:'required',timeout:60000}});
 if(!(new Uint8Array(r.response.authenticatorData)[32]&4))throw new Error('Phone unlock was not confirmed.');}
function settingsView(){const on=pmOn(),lk=lockKind();
 let ctl='';
 if(on){ctl=pmUi==='pass'?`<div class="glass search" style="margin:8px 0"><input id="pw1" type="password" autocomplete="current-password" placeholder="Your app passphrase"></div><div style="padding:8px 0 12px"><button class="refresh" id="pgo" style="margin-left:0">Turn off</button></div>`
  :lk==='pin'?`<div class="glass search" style="margin:8px 0"><input id="pn1" type="password" inputmode="numeric" pattern="[0-9]*" maxlength="4" autocomplete="off" placeholder="PIN"></div><div style="padding:8px 0 12px"><button class="refresh" id="pgo" style="margin-left:0">Turn off</button></div>`
  :`<div style="padding:8px 0 12px"><button class="refresh" id="pgo" style="margin-left:0">Turn off with phone unlock</button></div>`;
  ctl+=`<p class="note" style="padding:0 0 10px"><a href="#" id="plink" style="color:inherit">${pmUi==='pass'?'Back':'Forgot or cannot unlock? Use app passphrase'}</a></p>`;}
 else if(lk&&pmUi!=='pin'){ctl=`<div style="padding:8px 0 12px"><button class="refresh" id="pgo" style="margin-left:0">Turn on</button></div>`;}
 else if(pmUi==='pin'){ctl=`<div class="glass search" style="margin:8px 0"><input id="pn1" type="password" inputmode="numeric" pattern="[0-9]*" maxlength="4" autocomplete="off" placeholder="New PIN"></div><div class="glass search" style="margin:8px 0"><input id="pn2" type="password" inputmode="numeric" pattern="[0-9]*" maxlength="4" autocomplete="off" placeholder="Repeat PIN"></div><div style="padding:8px 0 12px"><button class="refresh" id="pgo" style="margin-left:0">Set PIN and turn on</button></div>`;}
 else ctl=`<div style="padding:8px 0 12px"><button class="refresh" id="pgo" style="margin-left:0">Turn on</button></div>`;
 const hint=on?(pmUi==='pass'?'Enter the passphrase you use to open this app.':(lk==='pin'?'Enter your PIN to turn it off.':'Your phone will ask for its screen lock, fingerprint or face to turn it off.')):(lk?'Turn on with one tap.':(pmUi==='pin'?'Choose a 4-digit PIN. You will need it to turn privacy off.':'The first time, your phone will ask you to confirm its screen lock so only you can turn it off.'));
 return `<section class="glass list"><div class="line" style="border:0"><span>Privacy mode<br><small>Blurs amounts, counts, article and customer names, stock numbers. Labels and layout stay clear.</small></span><b>${on?'On':'Off'}</b></div></section>
 <section class="glass list" style="margin-top:12px"><div class="line" style="border:0;padding-bottom:6px"><span>${hint}</span></div>${ctl}<p id="pme" class="note" style="padding:0 0 10px"></p></section>
${DEV()?`<section class="glass list" style="margin-top:12px"><div class="line" style="border:0"><span>Open app with phone lock<br><small>On (${DEV().mode==='prf'?'key sealed by phone':'phone lock gate'}). Passphrase still works as backup.</small></span><b>On</b></div><div style="padding:8px 0 12px"><button class="refresh" id="dvt" style="margin-left:0">Turn off</button></div></section>`:`<section class="glass list" style="margin-top:12px"><div class="line" style="border:0"><span>Open app with phone lock<br><small>Skip typing the passphrase. Enter it once to turn on.</small></span><b>Off</b></div><div class="glass search" style="margin:8px 0"><input id="dvp" type="password" autocomplete="current-password" placeholder="Your app passphrase"></div><div style="padding:8px 0 12px"><button class="refresh" id="dvt" style="margin-left:0">Turn on</button></div><p id="dve" class="note" style="padding:0 0 10px"></p></section>`}
 <p class="note" style="padding-bottom:0">Turning it off is protected by your phone's own lock (or a PIN if the phone cannot do that). This is a screen blur for casual viewers. It does not add encryption.</p>`;}
function bindSettings(){const go=$('#pgo');const dt=$('#dvt');if(dt)dt.onclick=async()=>{if(DEV()){LS.removeItem('dj_dev');LS.removeItem('dj_devno');render();return;}const m=$('#dve');m.textContent='';dt.disabled=true;try{const v=JSON.parse(LS.getItem('dj_vault'));let j;try{j=await unlockJwk(v,$('#dvp').value);}catch{m.textContent='Wrong passphrase.';dt.disabled=false;return;}await devEnable(j);render();}catch(x){dt.disabled=false;m.textContent=x&&x.name==='NotAllowedError'?'Cancelled.':(x&&x.message)||'Could not turn on.';}};
const pl=$('#plink');if(pl)pl.onclick=ev=>{ev.preventDefault();pmUi=pmUi==='pass'?'':'pass';render()};if(!go)return;
 go.onclick=async()=>{const m=$('#pme'),on=pmUi==='pass'||pmOn(),lk=lockKind();m.textContent='';go.disabled=true;try{
  if(!pmOn()){
   if(pmUi==='pin'){const v=$('#pn1').value;if(!/^\d{4}$/.test(v)){m.textContent='Enter 4 digits.';return;}if(v!==$('#pn2').value){m.textContent='PINs do not match.';return;}const salt=btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(16))));LS.setItem('dj_pin',JSON.stringify({salt,h:await pinHash(v,salt)}));LS.setItem('dj_lock','pin');LS.setItem('dj_pm','1');pmUi='';render();return;}
   if(!lk){try{await waRegister();}catch(x){pmUi='pin';render();const mm=$('#pme');if(mm)mm.textContent=(x&&x.name==='NotAllowedError'?'Phone unlock was cancelled or failed. ':'')+'Set a PIN instead.';return;}}
   LS.setItem('dj_pm','1');pmUi='';render();return;}
  if(pmUi==='pass'){const v=JSON.parse(LS.getItem('dj_vault')||'null');try{await unlock(v,$('#pw1').value);}catch{m.textContent='Wrong passphrase.';return;}LS.setItem('dj_pm','0');['dj_lock','dj_cred','dj_pin','dj_pinfail'].forEach(k=>LS.removeItem(k));pmUi='';render();return;}
  const f=JSON.parse(LS.getItem('dj_pinfail')||'{"n":0,"until":0}');if(Date.now()<f.until){m.textContent='Too many tries. Wait '+Math.ceil((f.until-Date.now())/1000)+'s.';return;}
  if(lk==='webauthn'){try{await waVerify();}catch(x){m.textContent=(x&&x.name==='NotAllowedError')?'Cancelled or not confirmed.':'Could not confirm. '+(x&&x.message||'');return;}LS.setItem('dj_pm','0');render();return;}
  const v=($('#pn1')||{}).value||'',p=JSON.parse(LS.getItem('dj_pin')||'null');if(p&&/^\d{4}$/.test(v)&&await pinHash(v,p.salt)===p.h){LS.removeItem('dj_pinfail');LS.setItem('dj_pm','0');render();}
  else{f.n++;if(f.n>=5)f.until=Date.now()+30000*Math.min(f.n-4,10);LS.setItem('dj_pinfail',JSON.stringify(f));m.textContent='Wrong PIN.';}
 }finally{const g=$('#pgo');if(g)g.disabled=false;}};}
function dayBills(kind,day){const n=v=>Number(v||0),iso=IST(),today=day===iso;
 if(kind==='o'){if(today)return (data.orders||[]).filter(o=>o.status!=='Cancelled').map(o=>({no:o.id,amt:o.amt,units:(o.items||[]).reduce((q,z)=>q+n(z.qty),0),ch:o.ch,order:true}));
  const e=(A(data.history)||[]).find(z=>z.d===day);return bl(e);}
 const R=data.retail,S=R&&A(R.stores)||[],sf=rf==='All'?S:S.filter(z=>z.name===rf);
 if(today){const l=[];sf.forEach(z=>(A(z.billList)||[]).forEach(b=>l.push({...b,store:z.name})));return l.length?l:null;}
 const e=(A(data.retailHistory)||[]).find(z=>z.d===day);if(!e)return null;
 if(rf!=='All'){const b=bl(e.by&&e.by[rf])||(Object.keys(e.by||{}).length<=1?bl(e):null);return b?b.map(x=>({...x,store:rf})):null;}
 if(bl(e))return bl(e);const l=[];Object.entries(e.by||{}).forEach(([s,v])=>(bl(v)||[]).forEach(b=>l.push({...b,store:s})));return l.length?l:null;}
function asOfMs(s){const x=s||{};for(const k of ['ts','generatedAt','atIso']){if(x[k]){const t=Date.parse(x[k]);if(!isNaN(t))return t;}}
 const m=String(x.at||'').match(/(\d{1,2})\s+([A-Za-z]{3})[a-z]*,?\s+(\d{1,2}):(\d{2})\s*([AP]M)/i);if(!m)return null;
 const mo='jan feb mar apr may jun jul aug sep oct nov dec'.split(' ').indexOf(m[2].toLowerCase());if(mo<0)return null;
 let h=+m[3]%12+(/p/i.test(m[5])?12:0);const now=new Date(),ist=new Date(now.getTime()+19800000);let y=ist.getUTCFullYear();
 let t=Date.UTC(y,mo,+m[1],h,+m[4])-19800000;if(t>now.getTime()+86400000)t=Date.UTC(y-1,mo,+m[1],h,+m[4])-19800000;return t;}
function freshBanner(s){const t=asOfMs(s),lbl=esc(String((s&&s.at)||''));if(t==null)return lbl?`<div class="asof"><span>Data as of ${lbl}</span></div>`:'';
 const mins=Math.max(0,Math.round((Date.now()-t)/60000)),stale=mins>90;const ago=mins<60?mins+' min ago':mins<1440?Math.floor(mins/60)+'h '+(mins%60)+'m ago':Math.floor(mins/1440)+'d ago';
 return `<div class="asof${stale?' stale':''}"><span>${stale?'Data may be stale · as of ':'Data as of '}${lbl}</span><small>${ago}</small></div>`;}
function render(){if(!data){root.innerHTML=shell(`<header>${logo}<div><h1>Dressjet Ops</h1><p>${esc(status)}</p></div><button class="refresh" id="rf">Refresh</button></header>`);$('#rf').onclick=load;return;}
 const s=data.snapshot,orders=data.orders,live=orders.filter(o=>o.status!=='Cancelled');const pend=A(data.pending)||[];const OI=ordInfo(s);
 let h=`<header>${detail?'<button class="refresh" id="bk">‹ Back</button>':logo}<div><h1>${detail?detailTitle():({today:'Today',orders:'Orders',best:'Best sellers',stock:'Low stock',retail:'Retail'})[tab]}</h1><p>Dressjet · ${esc(s.at)}${status?' · '+esc(status):''}</p></div><button class="refresh" id="rf">Refresh</button></header>${detail?'':freshBanner(s)}<main>`;
 if(detail==='set:privacy'){h+=settingsView();}
 else if(detail){h+=detailView(orders,live,pend,s);}
 else if(tab==='retail'){h+=retailView();}
 else if(tab==='today'){const CH=chanOf(s,OI),cn={};live.forEach(o=>cn[o.ch]=(cn[o.ch]||0)+1);const by=Object.entries(CH.m).map(([c,v])=>[c,(v&&typeof v==='object')?{amt:nn(v.amt!=null?v.amt:v.rev),n:v.n!=null?v.n:(v.orders!=null?v.orders:cn[c])}:{amt:nn(v),n:(CH.full?null:cn[c])}]).sort((a,b)=>(a[0]==='Not itemised')-(b[0]==='Not itemised')||b[1].amt-a[1].amt),max=Math.max(1,...by.map(c=>c[1].amt));
  const RT=data.retail&&A(data.retail.stores),rs=RT?RT.reduce((q,z)=>q+Number(z.sales||0),0):0,rb=RT?RT.reduce((q,z)=>q+Number(z.bills||0),0):0,ru=RT?RT.reduce((q,z)=>q+Number(z.units||0),0):0;
  if(RT){h+=`<div class="grid2" style="margin-bottom:12px"><section class="glass tile" data-d="r:rev" style="padding:18px"><span class="eyebrow">Online</span><b style="font-family:var(--serif,inherit);font-size:26px;margin-top:6px">${inr(s.revenue)}</b><span>${SV(ordN(OI)+' orders · '+s.items+' items')}</span><span style="opacity:.6;font-size:11px;margin-top:4px">incl. GST · yesterday ${SV(inr(s.revenuePrev))}</span></section><section class="glass tile" data-t="retail" style="padding:18px"><span class="eyebrow">Retail</span><b style="font-family:var(--serif,inherit);font-size:26px;margin-top:6px">${inr(rs)}</b><span>${SV(rb+' bills · '+ru+' units')}</span><span style="opacity:.6;font-size:11px;margin-top:4px">incl. GST${data.retail.at?' · '+esc(data.retail.at):''}</span></section></div><section class="glass" style="padding:14px 18px;margin-bottom:12px"><div class="line" style="border:0;padding:0"><span class="eyebrow">Combined today</span><b style="font-family:var(--serif,inherit);font-size:22px">${inr(Number(s.revenue)+rs)}</b></div></section>`;}
  else h+=`<section class="glass hero" data-d="r:rev"><span class="eyebrow">Today's revenue</span><div class="big">${inr(s.revenue)}</div><div class="sub"><span class="chip">so far</span> Yesterday full day: ${SV(inr(s.revenuePrev))}</div><div class="split"><div><b>${s.items}</b><span>order items</span></div><div><b>${ordN(OI)}</b><span>orders</span></div><div><b>${(()=>{const dn=OI.tot!=null?Math.max(1,OI.tot):(OI.partial?null:Math.max(1,OI.live.length));return inr(Math.round(dn?OI.rev/dn:OI.listed/Math.max(1,OI.live.length)))})()}</b><span>${OI.partial&&OI.tot==null?'avg (listed)':'avg order'}</span></div></div></section>`;h+=`
  ${histView(s)}
  <h2>Needs attention</h2><div class="grid2">${s.alerts.map(a=>`<div class="glass tile ${a.tone}" data-d="p:${esc(a.k)}"><b>${a.v}</b><span>${esc(a.k)}</span></div>`).join('')}</div>
  ${attnToday()}<h2>Channels today</h2><section class="glass list">${by.map(([c,v])=>`<div class="chrow" ${c==='Not itemised'?'':'data-d="c:'+esc(c)+'"'}><div class="chtop"><span>${esc(c)}</span><span>${inr(v.amt)}${v.n?' · '+v.n:''}</span></div><div class="bar"><i style="width:${v.amt/max*100}%"></i></div></div>`).join('')}</section>${OI.partial&&!CH.full?`<p class="note" style="padding:6px 0 0">Only ${orders.length} of ${OI.tot!=null?OI.tot:'today\'s'} orders are itemised. "Not itemised" is the rest of today\'s revenue.</p>`:''}
  <h2>Pending today</h2><section class="glass list">${s.pipeline.map(p=>`<div class="line" data-d="p:${esc(p.k)}"><span>${esc(p.k)}</span><b>${p.v}</b></div>`).join('')}</section>
${(()=>{let x='';
   const pd=A(data.pending);x+=`<h2>Pending dispatch${pd?' · '+pd.length:''}</h2>`+(pd&&pd.length>25?`<p class="note" style="padding:0 0 8px;text-align:left">Showing the 25 oldest of ${pd.length}.</p>`:'')+(pd?`<section class="ol">${[...pd].sort((a,b)=>b.ageH-a.ageH).slice(0,25).map(o=>`<article class="glass order" data-d="o:${esc(o.id)}"><div class="otop"><b>${esc(o.id)}</b><span class="st ${o.ageH>=48?'cancelled':o.ageH>=24?'pending_verification':'complete'}">${ageTxt(o.ageH)} old</span></div><div class="osku">${esc(o.skus||'')}</div><div class="ometa"><span>${esc(o.ch)} · ${esc(o.status)}</span><b>${o.amt?inr(o.amt):''}</b></div></article>`).join('')}</section>`:none('Waiting for dispatch data'));return x;})()}
  <h2>Catalog sync</h2><section class="glass list">${s.sync.map(p=>`<div class="line"><span>${esc(p.k)}</span><b>${p.v}</b></div>`).join('')}<div class="line"><span>Channel listings</span><b>${Number(s.listings).toLocaleString('en-IN')}</b></div></section>`;}
 else if(tab==='stock'&&A(data.retailStock)&&sv==='retail'){h+=`<div class="pills"><button data-sv="online">Online</button><button data-sv="retail" class="on">Retail</button></div>`+attnStock('retail')+retailStockView();}
 else if(tab==='stock'){const st=A(data.stock);if(A(data.retailStock))h+=`<div class="pills"><button data-sv="online" class="on">Online</button><button data-sv="retail">Retail</button></div>`;h+=attnStock('online');const wk=(data.sellers&&data.sellers.week)||[];const per={};wk.forEach(x=>{if(x.qty)per[x.sku]=x.qty/7});
  const rows=st?st.map(x=>{const pd=x.perDay!=null?x.perDay:(per[x.sku]||0);return {...x,pd,days:pd>0?x.onHand/pd:null}}).sort((a,b)=>(a.days===null)-(b.days===null)||(a.days!==null?a.days-b.days:a.onHand-b.onHand)):[];
  const SM0=data.stockMeta,T=(SM0?null:data.stockTotals)||(SM0?{units:SM0.units,skus:SM0.tot,oosPct:Math.round(SM0.oos/Math.max(1,rows.length)*100),oosN:SM0.oos,part:1}:null);h+=T?`<div class="grid2"><div class="glass tile"><b>${Number(T.units).toLocaleString('en-IN')}</b><span>Units in stock${T.part?' (reachable SKUs)':''}</span></div><div class="glass tile"><b>${Number(T.skus).toLocaleString('en-IN')}</b><span>SKUs${SM0?' · '+SM0.cov+' reachable':''}</span></div></div><div class="glass tile ${T.oosPct>=25?'amber':''}" style="margin-top:12px"><b>${T.oosPct}%</b><span>Out of stock${T.oosN!=null?' · '+T.oosN+' SKUs':''}${T.part?' (of '+SM0.cov+' reachable)':''}</span></div><h2>${rows.some(x=>x.days!==null)?'Fast sellers':'Lowest stock'}</h2>`:'';
  const SM=data.stockMeta,RF=rows.filter(x=>!rq||(x.sku+' '+(x.name||'')).toLowerCase().includes(rq.toLowerCase()));h+=st?`<div class="glass search" style="margin:12px 0"><input id="rq" placeholder="Search SKU or name" value="${esc(rq)}"></div><section class="glass list">${RF.length?RF.slice(0,100).map(x=>`<div class="line" data-d="s:${esc(x.sku)}"><span>${SV(esc(x.sku))}<br><small>${x.pd>0?x.pd.toFixed(1)+'/day':'selling pace n/a'}</small></span><b class="${(x.days!==null?x.days<7:x.onHand<10)?'low':''}">${x.days!==null?(x.days<1?'<1':Math.round(x.days))+'d left · ':''}${x.onHand} in stock</b></div>`).join(''):'<div class="empty">No SKU matches.</div>'}</section><p class="note">${rows.some(x=>x.days!==null)?'Sorted by days left at recent pace':'Lowest stock first (selling pace not available)'}. Showing ${Math.min(100,RF.length)} of ${RF.length}${rq?' matching':''} ${SM?'reachable SKUs · '+SM.cov+' of '+SM.tot.toLocaleString('en-IN')+' SKUs reachable (the rest are not accessible to this login)':(T&&Number(T.skus)>rows.length?'listed SKUs of '+Number(T.skus).toLocaleString('en-IN'):'SKUs')}.</p>`:none('Waiting for stock data');} else if(tab==='best'){const t={};live.forEach(o=>o.items.forEach(i=>{const x=(t[i.sku]=t[i.sku]||{sku:i.sku,qty:0,orders:0});x.qty+=i.qty;x.orders++}));
  const S=data.sellers||{};const P=[['today','Today',Object.values(t).sort((a,b)=>b.qty-a.qty||b.orders-a.orders)],['week','Week',A(S.week)],['month','Month',A(S.month)],['quarter','90 days',A(S.quarter)]].filter(p=>p[2]||p[0]==='today');
  if(!P.find(p=>p[0]===bs))bs='today';const rows=P.find(p=>p[0]===bs)[2]||[];const val=r=>r.qty!=null?r.qty:(r.rev||0);const mx=Math.max(1,...rows.map(val));
  h+=`<div class="pills">${P.map(p=>`<button data-b="${p[0]}" class="${bs===p[0]?'on':''}">${p[1]}</button>`).join('')}</div><section class="glass list">${rows.length?rows.slice(0,15).map((r,n)=>`<div class="chrow" data-d="s:${esc(r.sku)}"><div class="chtop"><span>${n+1}. ${SV(esc(r.sku))}</span><span>${r.qty!=null?r.qty+' sold':''}${r.qty!=null&&r.rev?' · ':''}${r.rev?inr(r.rev):''}</span></div><div class="bar"><i style="width:${val(r)/mx*100}%"></i></div></div>`).join(''):'<div class="empty">No sales yet.</div>'}</section><p class="note">${bs==='today'?'Units from the '+live.length+' itemised non-cancelled orders'+(OI.partial?' (today has more).':'.'):'By revenue from the Sales dashboard.'}</p>`+bestBlock();}
 else{const chans=['All',...new Set(orders.map(o=>o.ch))];const list=orders.filter(o=>(ch==='All'||o.ch===ch)&&(!q||(o.id+o.items.map(i=>i.sku).join(' ')).toLowerCase().includes(q.toLowerCase())));
  h+=`<p class="note" style="padding:0 0 8px;text-align:left">${OI.all!=null&&OI.all>orders.length?'Showing the latest '+orders.length+' of '+OI.all+' orders today (incl. cancelled).':(OI.partial?'Showing the latest '+orders.length+' orders. Today has more than this list holds.':orders.length+' orders today.')}</p><div class="glass search"><input id="q" placeholder="Search order or SKU" value="${esc(q)}"></div><div class="pills">${chans.map(c=>`<button data-c="${esc(c)}" class="${c===ch?'on':''}">${esc(c)}</button>`).join('')}</div><section class="ol">${list.length?list.map(o=>`<article class="glass order" data-d="o:${esc(o.id)}"><div class="otop"><b>${esc(o.id)}</b><span class="st ${o.status.toLowerCase()}">${esc(o.status)}</span></div><div class="osku">${o.items.map(i=>esc(i.sku)+(i.qty>1?' ×'+i.qty:'')).join(', ')}</div><div class="ometa"><span>${esc(o.ch)} · ${esc(o.pay)} · ${esc(o.time)}</span><b>${o.amt?inr(o.amt):'—'}</b></div></article>`).join(''):'<div class="glass empty">No orders match.</div>'}</section>`;}
 if(!detail)h+=`<section class="glass list pmrow"><div class="line" data-pm="1" style="border:0"><span>Settings<br><small>Privacy mode: ${pmOn()?'On':'Off'}</small></span><b>›</b></div></section>`;
 h+=`</main><nav class="glass tabbar"><button data-t="today" class="${tab==='today'?'on':''}">Today</button><button data-t="orders" class="${tab==='orders'?'on':''}">Orders</button><button data-t="best" class="${tab==='best'?'on':''}">Sellers</button><button data-t="stock" class="${tab==='stock'?'on':''}">Stock</button><button data-t="retail" class="${tab==='retail'?'on':''}">Retail</button></nav>`;
 document.body.classList.toggle('pm',pmOn());if(pmOn())document.body.classList.add('pmx');document.body.classList.toggle('pmd',!!detail&&/^(o|s|rb|db):/.test(detail));root.innerHTML=shell(h);$('#rf').onclick=load;document.querySelectorAll('[data-pm]').forEach(b=>b.onclick=()=>{detail='set:privacy';window.scrollTo(0,0);render()});document.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{tab=b.dataset.t;detail=null;render()});document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{detail=b.dataset.d;window.scrollTo(0,0);render()});bindSettings();const bk=$('#bk');if(bk)bk.onclick=()=>{if(history.state&&history.state.n)history.back();else{detail=null;render();}};document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{tab=b.dataset.go;detail=null;window.scrollTo(0,0);render()});[['bw',v=>bwin=+v],['bm',v=>bmet=v],['bch',v=>bchn=v]].forEach(([k,f])=>document.querySelectorAll('[data-'+k+']').forEach(b=>b.onclick=()=>{f(b.dataset[k]);render()}));motion();nav();document.querySelectorAll('[data-h]').forEach(b=>b.onclick=()=>{hs=+b.dataset.h;render()});document.querySelectorAll('[data-b]').forEach(b=>b.onclick=()=>{bs=b.dataset.b;render()});document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{ch=b.dataset.c;render()});
 document.querySelectorAll('[data-rf]').forEach(b=>b.onclick=()=>{rf=b.dataset.rf;render()});document.querySelectorAll('[data-sv]').forEach(b=>b.onclick=()=>{sv=b.dataset.sv;rq='';render()});const ri=$('#rq');if(ri)ri.oninput=e=>{rq=e.target.value;const p=e.target.selectionStart;render();const n=$('#rq');n.focus();n.setSelectionRange(p,p)};const qi=$('#q');if(qi)qi.oninput=e=>{q=e.target.value;const p=e.target.selectionStart;render();const n=$('#q');n.focus();n.setSelectionRange(p,p)};}

const nn=v=>Number(v||0);
const IST=()=>new Date(Date.now()+19800000).toISOString().slice(0,10);
const addD=(iso,k)=>new Date(Date.parse(iso+'T00:00:00Z')+k*864e5).toISOString().slice(0,10);
function calWin(full,iso,N){const by={};full.forEach(x=>{if(x&&x.d)by[x.d]=x});const dates=[];for(let k=N;k>=1;k--)dates.push(addD(iso,-k));const cur=dates.map(z=>by[z]).filter(Boolean),prev=[];for(let k=2*N;k>N;k--){const e=by[addD(iso,-k)];if(e)prev.push(e);}return {dates,by,cur,prev};}
function ordInfo(s){const o=data.orders||[],live=o.filter(x=>x.status!=='Cancelled'),listed=live.reduce((q,x)=>q+nn(x.amt),0),rev=nn(s.revenue);const ct=s.channelsToday||data.channelsToday||null;const tot=s.orderCount!=null?nn(s.orderCount):(ct&&ct.orders!=null&&ct.cancelled!=null?nn(ct.orders)-nn(ct.cancelled):null);const gap=Math.round(rev-listed);const partial=(tot!=null&&tot>live.length)||(tot==null&&gap>Math.max(500,rev*.02));const canc=o.length-live.length;const all=tot!=null?tot+nn(ct&&ct.cancelled!=null?ct.cancelled:canc):null;return {o,live,listed,rev,tot,all,gap,partial,canc,ct,n:tot!=null?tot:live.length,plus:partial&&tot==null};}
const ordN=I=>I.n+(I.plus?'+':'');
function chanOf(s,I){if(!(s.ch&&typeof s.ch==='object')&&I.ct&&Array.isArray(I.ct.by)&&I.ct.by.length){const m={};I.ct.by.forEach(x=>{m[x.ch]={amt:nn(x.rev),n:nn(x.orders)}});return {m,full:true};}const T=[s.ch,s.chTotals,s.channelTotals,s.byChannel].find(x=>x&&typeof x==='object'&&!Array.isArray(x)&&Object.keys(x).length);if(T)return {m:T,full:true};const m={};I.live.forEach(o=>m[o.ch]=(m[o.ch]||0)+nn(o.amt));if(I.partial&&I.gap>0)m['Not itemised']=I.gap;return {m,full:false};}
let bwin=30,bchn='online',bmet='units';
function onStockRows(){const st=A(data.stock);if(!st)return null;const per={};((data.sellers&&data.sellers.week)||[]).forEach(x=>{if(x.qty)per[x.sku]=x.qty/7});return st.map(x=>{const pd=x.perDay!=null?x.perDay:(per[x.sku]||0);return {sku:String(x.sku),name:x.name||'',onHand:nn(x.onHand),pd,days:pd>0?nn(x.onHand)/pd:null,ch:'Online'}});}
function rtStockRows(){const RS=A(data.retailStock);if(!RS)return null;const m={};RS.forEach(x=>{const k=String(x.sku),r=(m[k]=m[k]||{sku:k,name:x.name||'',onHand:0,pd:0,days:null,ch:'Retail',by:[]});r.onHand+=nn(x.onHand);if(x.name&&!r.name)r.name=x.name;if(x.store)r.by.push(x.store+' '+nn(x.onHand));});return Object.values(m);}
function attn(chn){const o=chn!=='retail'?onStockRows():null,r=chn!=='online'?rtStockRows():null;const all=[...(o||[]),...(r||[])];if(!all.length)return null;
 const low=all.filter(x=>x.onHand<=3).sort((p,q)=>p.onHand-q.onHand||p.sku.localeCompare(q.sku));const soon=all.filter(x=>x.onHand>3&&x.days!==null&&x.days<=7).sort((p,q)=>p.days-q.days);return {low,soon};}
const arow=x=>`<div class="line"><span>${SV(esc(x.sku))}<br><small>${x.ch}${x.name?' · '+esc(x.name):''}${x.by&&x.by.length>1?' · '+esc(x.by.join(', ')):''}</small></span><b class="low">${x.onHand<=0?'Out of stock':(x.days!==null&&x.onHand>3?(x.days<1?'<1':Math.round(x.days))+'d left · ':'')+x.onHand+' left'}</b></div>`;
function attnToday(){const t=attn('all');if(!t||(!t.low.length&&!t.soon.length))return '';const rows=[...t.soon.slice(0,3),...t.low].slice(0,6);const n=t.low.length+t.soon.length;
 return `<h2>Stock alerts</h2><section class="glass list">${rows.map(arow).join('')}<div class="line" data-go="stock" style="border:0"><span><small>${n} item${n>1?'s':''} low (3 or fewer units${t.soon.length?', or under 7 days of cover':''})</small></span><b><small>See all ›</small></b></div></section>`;}
function attnStock(chn){const t=attn(chn);if(!t)return '';if(!t.low.length&&!t.soon.length)return `<h2>Stock alerts</h2><section class="glass list" style="margin-bottom:12px"><div class="line"><span>Nothing at 3 units or less${chn==='online'?', no fast sellers close to running out':''}.</span><b>✓</b></div></section>`;
 return `<h2>Stock alerts</h2><section class="glass list" style="margin-bottom:12px">${t.soon.length?`<div class="line" style="border:0"><span><small>Likely to run out within 7 days</small></span></div>`+t.soon.slice(0,10).map(arow).join(''):''}${t.low.length?`<div class="line" style="border:0"><span><small>3 units or fewer (${t.low.length})</small></span></div>`+t.low.slice(0,15).map(arow).join(''):''}</section>`;}
function itemsOf(e,chn){if(!e)return null;if(chn==='online')return A(e.itemList)||(Array.isArray(e.items)?A(e.items):null)||(bl(e)?bl(e).flatMap(b=>A(b.items)||[]):null);
 if(Array.isArray(e.items)&&e.items.length)return e.items;if(e.by){const l=[];let any=false;Object.values(e.by).forEach(v=>{if(v&&Array.isArray(v.items)&&v.items.length){any=true;l.push(...v.items);}});if(any)return l;}
 const b=bl(e);if(b){const l=b.flatMap(z=>A(z.items)||[]);return l.length?l:null;}return null;}
function sales(chn,days){const sm=A(data[(chn==='online'?'online':'retail')+days]);if(sm){const m={};sm.forEach(i=>{const k=String(i.sku);const r=(m[k]=m[k]||{sku:k,name:i.name||'',qty:null,amt:0});if(i.qty!=null)r.qty=(r.qty||0)+nn(i.qty);r.amt+=nn(i.amt);});return {m,cov:days,span:days,summary:true};}
 const H=A(chn==='online'?data.history:data.retailHistory);if(!H)return null;const ds=H.map(x=>x.d).filter(Boolean).sort();if(!ds.length)return null;
 const last=new Date(ds[ds.length-1]+'T00:00:00').getTime(),cut=last-(days-1)*864e5;const m={};let cov=0;
 H.forEach(e=>{if(!e.d||new Date(e.d+'T00:00:00').getTime()<cut)return;const it=itemsOf(e,chn);if(!it)return;cov++;it.forEach(i=>{const k=String(i.sku);const r=(m[k]=m[k]||{sku:k,name:i.name||'',qty:0,amt:0});r.qty+=nn(i.qty);r.amt+=nn(i.amt);if(i.name&&!r.name)r.name=i.name;});});
 return {m,cov,span:H.filter(e=>e.d&&new Date(e.d+'T00:00:00').getTime()>=cut).length};}
function bestBlock(){const hasR=!!A(data.retailHistory);if(!hasR&&bchn==='retail')bchn='online';const sl=sales(bchn,bwin);
 const pill=(attr,v,cur,l)=>`<button data-${attr}="${v}" class="${String(cur)===String(v)?'on':''}">${l}</button>`;
 let h=`<h2>Best and slowest</h2><div class="pills">${pill('bw',7,bwin,'7 days')}${pill('bw',30,bwin,'30 days')}${pill('bm','units',bmet,'By units')}${pill('bm','rev',bmet,'By revenue')}${hasR?pill('bch','online',bchn,'Online')+pill('bch','retail',bchn,'Retail'):''}</div>`;
 const rows=sl?Object.values(sl.m):[];
 if(!rows.length){const fb=bchn==='online'?(bwin===7?(data.sellers&&data.sellers.week):(data.sellers&&data.sellers.month)):null;
  if(A(fb))return h+`<section class="glass list">${fb.slice(0,10).map((r,n)=>`<div class="line"><span>${n+1}. ${SV(esc(r.sku))}</span><b>${r.qty!=null?r.qty+' sold':''}${r.qty!=null&&r.rev?' · ':''}${r.rev?inr(r.rev):''}</b></div>`).join('')}</section><p class="note">Online shows revenue only (units and dead stock are not available online).</p>`;
  return h+`<section class="glass list"><div class="line"><span>Item-level sales are not available yet for ${bchn==='retail'?'retail':'online'}.</span><b>—</b></div></section>`;}
 const hasAmt=rows.some(r=>r.amt>0),hasQty=rows.some(r=>r.qty>0);const k=(bmet==='rev'&&hasAmt)||!hasQty?'amt':'qty';
 const sorted=rows.slice().sort((p,q)=>nn(q[k])-nn(p[k])||p.sku.localeCompare(q.sku));const fmt=r=>(r.qty!=null?`${r.qty} unit${r.qty===1?'':'s'}`:'')+(r.qty!=null&&r.amt?' · ':'')+(r.amt?inr(r.amt):'');
 const row=(r,n)=>`<div class="line"><span>${n!=null?n+'. ':''}${SV(esc(r.sku))}${r.name?'<br><small>'+esc(r.name)+'</small>':''}</span><b>${fmt(r)}</b></div>`;
 h+=`<section class="glass list"><div class="line" style="border:0"><span><small>Top ${Math.min(8,sorted.length)}</small></span></div>${sorted.slice(0,8).map((r,n)=>row(r,n+1)).join('')}</section>`;
 const bot=sorted.length>8?sorted.slice(-Math.min(8,sorted.length-8)).reverse():[];if(bot.length)h+=`<section class="glass list" style="margin-top:12px"><div class="line" style="border:0"><span><small>Slowest that still sold</small></span></div>${bot.map(r=>row(r)).join('')}</section>`;
 const stk=bchn==='online'?onStockRows():rtStockRows();
 if(bwin===30){const s30=sl,full=s30.span>0&&s30.cov>=s30.span;
  const pre=A(bchn==='online'?data.deadStock:data.retailDead);
  if(pre)h+=`<h2>No sales in 30 days, stock on hand</h2><section class="glass list">${pre.filter(x=>nn(x.onHand)>0).slice(0,15).map(x=>`<div class="line"><span>${SV(esc(x.sku))}${x.name?'<br><small>'+esc(x.name)+'</small>':''}</span><b>${nn(x.onHand)} in stock</b></div>`).join('')}</section>${bchn==='online'&&data._deadDerived&&data.stockMeta?`<p class="note">Only ${data.stockMeta.cov} of ${data.stockMeta.tot.toLocaleString('en-IN')} SKUs are reachable, so this list is partial.</p>`:''}`;
  else if(stk&&bchn!=='online'){const sold=new Set(rows.map(r=>r.sku));const dead=stk.filter(x=>x.onHand>0&&!sold.has(x.sku)).sort((p,q)=>q.onHand-p.onHand);
   const partial=!full||s30.span<30;
   h+=`<h2>No sales in 30 days, stock on hand</h2><section class="glass list">${dead.length?dead.slice(0,15).map(x=>`<div class="line"><span>${SV(esc(x.sku))}${x.name?'<br><small>'+esc(x.name)+'</small>':''}</span><b>${x.onHand} in stock</b></div>`).join(''):'<div class="line"><span>None found in the stock list.</span><b>✓</b></div>'}</section>${partial?`<p class="note">Based on ${s30.cov} day${s30.cov===1?'':'s'} of item sales, so this list may be incomplete.</p>`:''}`;}
  else if(bchn!=='online')h+=`<h2>No sales in 30 days, stock on hand</h2><section class="glass list"><div class="line"><span>Waiting for ${bchn} stock data.</span><b>—</b></div></section>`;}
 else if(sl.cov<sl.span)h+=`<p class="note">Item detail for ${sl.cov} of ${sl.span} days.</p>`;
 return h;}
let lastAnim=null,dir='f',lastX=null;const RM=matchMedia('(prefers-reduced-motion: reduce)').matches;
function countUp(el){const m=(el.textContent||'').trim().match(/^(₹)?([\d,]+)$/);if(!m)return;const to=+m[2].replace(/,/g,'');if(!to||to>1e9)return;const pre=m[1]||'',t0=performance.now(),D=650;
 const f=t=>{const p=Math.min(1,(t-t0)/D),e=1-Math.pow(1-p,3);el.textContent=pre+Math.round(to*e).toLocaleString('en-IN');if(p<1)requestAnimationFrame(f);};el.textContent=pre+'0';requestAnimationFrame(f);}
function motion(){const k=navKey(),an=k!==lastAnim;lastAnim=k;const mn=document.querySelector('main'),tb=document.querySelector('.tabbar'),ind=tb&&tb.querySelector('.ind'),on=tb&&tb.querySelector('button.on');
 if(tb&&on){let sp=ind;if(!sp){sp=document.createElement('span');sp.className='ind';tb.insertBefore(sp,tb.firstChild);}const x=on.offsetLeft;sp.style.width=on.offsetWidth+'px';sp.style.transform='translate3d('+x+'px,0,0)';
  if(!RM&&lastX!==null&&lastX!==x&&sp.animate)sp.animate([{transform:'translate3d('+lastX+'px,0,0)'},{transform:'translate3d('+x+'px,0,0)'}],{duration:420,easing:'cubic-bezier(.3,1.25,.4,1)'});lastX=x;}
 if(an&&!RM&&mn){mn.classList.add('anim',dir);[...mn.children].slice(0,8).forEach((c,i)=>c.style.setProperty('--i',i));
  mn.querySelectorAll('svg g[data-d] rect[fill^="url"]').forEach((r,i)=>r.style.animationDelay=Math.min(i,30)*14+'ms');
  mn.querySelectorAll('.bar i').forEach((r,i)=>r.style.animationDelay=(80+Math.min(i,12)*40)+'ms');
  if(!pmOn())mn.querySelectorAll('.big,.tile b').forEach(countUp);}
 dir='f';}
let navOn=false,exitArm=false;const navKey=()=>(detail||'')+'|'+tab;
function toast(m){let t=$('#toast');if(!t){t=document.createElement('div');t.id='toast';t.style.cssText='position:fixed;left:50%;bottom:110px;transform:translateX(-50%);background:rgba(30,26,22,.95);color:#f3e9d6;padding:10px 16px;border-radius:14px;font-size:14px;z-index:99;border:1px solid rgba(255,255,255,.12)';document.body.appendChild(t);}t.textContent=m;t.style.display='block';clearTimeout(t._h);t._h=setTimeout(()=>t.style.display='none',2000);}
function nav(){if(!navOn)return;const k=navKey(),s=history.state;if(s&&s.n&&s.k===k)return;
 const dp=(s&&s.n)||1;if(k==='|today'){if(dp>1)history.go(1-dp);}else history.pushState({n:dp+1,k,d:detail,t:tab},'');}
document.body.classList.add('nt');if(pmOn())document.body.classList.add('pm','pmx');setTimeout(()=>document.body.classList.remove('nt'),900);
function initNav(){if(navOn)return;navOn=true;
 history.replaceState({g:1},'');history.pushState({n:1,k:navKey(),d:detail,t:tab},'');
 addEventListener('popstate',e=>{const s=e.state;
  if(s&&s.g){if(exitArm){exitArm=false;history.back();return;}exitArm=true;toast('Press back again to exit');setTimeout(()=>{exitArm=false},2000);history.pushState({n:1,k:'|today',d:null,t:'today'},'');detail=null;tab='today';render();return;}
  if(s&&s.n){dir='b';detail=s.d;tab=s.t;window.scrollTo(0,0);render();}});}
let timer;function start(){initNav();load();clearInterval(timer);timer=setInterval(()=>{if(!document.hidden)load()},((window.DJ_CONFIG||{}).pollMinutes||5)*60000);}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&priv)load()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
lockScreen();
