import {setup,unlock,decryptPayload,kid} from './crypto.js?v=2';
const $=s=>document.querySelector(s),root=$('#root');
const inr=n=>'₹'+Number(n).toLocaleString('en-IN');
const A=x=>Array.isArray(x)&&x.length?x:null;const pct=(a,b)=>b?Math.round((a-b)/b*100):null;const arrow=p=>p===null?'':(p>=0?'▲ ':'▼ ')+Math.abs(p)+'%';const ageTxt=h=>h<24?Math.round(h)+'h':Math.floor(h/24)+'d '+Math.round(h%24)+'h';const none=m=>`<div class="glass empty">${m}</div>`;
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const LS=localStorage;let hs=7,detail=null,bs='today',priv=null,myKid=null,data=null,tab='today',q='',ch='All',status='';
const shell=inner=>`<div class="app"><div class="blob b1"></div><div class="blob b2"></div><div class="blob b3"></div>${inner}</div>`;
const logo='<img class="logo" src="icon-192.png" alt="Dressjet">';
function lockScreen(){const v=JSON.parse(LS.getItem('dj_vault')||'null');
 root.innerHTML=shell(`<div class="lock">${logo}<h1>Dressjet Ops</h1>${v?`<p>Enter your passphrase to open.</p><div class="glass"><input id="pw" type="password" autocomplete="current-password" placeholder="Passphrase"><button class="btn" id="go">Unlock</button><div class="err" id="err"></div></div>`:
 `<p>First time on this phone. Choose a passphrase. It never leaves this phone and cannot be recovered, so keep it somewhere safe.</p><div class="glass"><input id="pw" type="password" placeholder="Passphrase (10+ characters)"><input id="pw2" type="password" placeholder="Repeat passphrase"><button class="btn" id="go">Create</button><div class="err" id="err"></div></div>`}</div>`);
 $('#go').onclick=async()=>{const e=$('#err');e.textContent='';const pw=$('#pw').value;
  try{ if(v){priv=await unlock(v,pw);myKid=await kid(v.pub);start();}
   else{ if(pw.length<10){e.textContent='Use at least 10 characters.';return;} if(pw!==$('#pw2').value){e.textContent='Passphrases do not match.';return;}
    $('#go').textContent='Working...';const r=await setup(pw);LS.setItem('dj_vault',JSON.stringify(r.vault));showKey(r.pubText);} }
  catch(x){e.textContent=v?'Wrong passphrase.':'Something went wrong: '+x.message;$('#go').textContent=v?'Unlock':'Create';}};}
function showKey(t){root.innerHTML=shell(`<div class="lock">${logo}<h1>Almost done</h1><p>Send this public key to your assistant. It is not secret. It lets updates be locked so only this phone can read them.</p><div class="glass"><div class="keybox" id="k">${esc(t)}</div><button class="btn" id="cp">Copy key</button><button class="btn alt" id="sh">Share key</button><button class="btn alt" id="nx">Continue</button></div></div>`);
 $('#cp').onclick=async()=>{try{await navigator.clipboard.writeText(t);$('#cp').textContent='Copied'}catch{}};
 $('#sh').onclick=()=>navigator.share?navigator.share({text:t}):0;$('#nx').onclick=lockScreen;}
async function fetchLatest(){const repo=(window.DJ_CONFIG||{}).repo;
 const r=await fetch(`https://api.github.com/repos/${repo}/issues/comments?sort=created&direction=desc&per_page=1&_=${Date.now()}`,{cache:'no-store',headers:{Accept:'application/vnd.github+json'}});
 if(!r.ok)throw new Error('GitHub '+r.status);const j=await r.json();if(!j.length)throw new Error('No data yet');
 const body=j[0].body.trim().replace(/^```(json)?/,'').replace(/```$/,'').trim();LS.setItem('dj_last',body);return body;}
async function load(){try{status='Updating...';render();let b;try{b=await fetchLatest();status='';}catch(e){b=LS.getItem('dj_last');status=b?'Offline, showing last saved data':'No data yet: '+e.message;if(!b){render();return;}}
 data=await decryptPayload(JSON.parse(b),priv,myKid);}catch(e){status='Could not read update: '+e.message;}render();}

function detailTitle(){const i=detail.indexOf(':'),t=detail.slice(0,i),k=detail.slice(i+1);return t==='o'?'Order '+k:t==='c'?k:t==='s'?k:t==='r'?'Revenue today':k;}
function ocard(o){const items=o.items?o.items.map(i=>esc(i.sku)+(i.qty>1?' ×'+i.qty:'')).join(', '):esc(o.skus||'');const st=o.status||'';
 return `<article class="glass order" data-d="o:${esc(o.id)}"><div class="otop"><b>${esc(o.id)}</b><span class="st ${st.toLowerCase()}">${esc(st)}</span></div><div class="osku">${items}</div><div class="ometa"><span>${esc(o.ch)}${o.pay?' · '+esc(o.pay):''} · ${o.ageH!=null?ageTxt(o.ageH)+' old':esc(o.time||'')}</span><b>${o.amt?inr(o.amt):'—'}</b></div></article>`;}
function kv(a,b){return `<div class="line"><span>${a}</span><b>${b}</b></div>`;}
function detailView(orders,live,pend,s){const i=detail.indexOf(':'),t=detail.slice(0,i),k=detail.slice(i+1);
 if(t==='o'){const o=orders.find(x=>String(x.id)===k)||pend.find(x=>String(x.id)===k);if(!o)return none('Order not in the latest data.');
  const items=o.items?o.items:(o.skus?String(o.skus).split(',').map(z=>({sku:z.trim(),qty:1})):[]);const units=items.reduce((a,b)=>a+b.qty,0);
  return `<section class="glass list">${kv('Status',esc(o.status))}${kv('Channel',esc(o.ch))}${o.pay?kv('Payment',esc(o.pay)):''}${kv('Amount',o.amt?inr(o.amt):'—')}${kv(o.ageH!=null?'Age':'Placed',o.ageH!=null?ageTxt(o.ageH):'Today '+esc(o.time))}${kv('Units',units||'—')}</section><h2>Items</h2><section class="glass list">${items.map(z=>kv(esc(z.sku),'× '+z.qty)).join('')||'<div class="empty">No item detail.</div>'}</section>`;}
 if(t==='c'){const l=live.filter(o=>o.ch===k),tot=l.reduce((a,b)=>a+b.amt,0),sk={};l.forEach(o=>o.items.forEach(z=>sk[z.sku]=(sk[z.sku]||0)+z.qty));
  const top=Object.entries(sk).sort((a,b)=>b[1]-a[1]).slice(0,5),cod=l.filter(o=>/cod/i.test(o.pay)).length;
  return `<section class="glass list">${kv('Revenue today',inr(tot))}${kv('Orders',l.length)}${kv('Avg order',inr(Math.round(tot/Math.max(1,l.length))))}${kv('COD orders',cod)}</section>${top.length?'<h2>Top SKUs</h2><section class="glass list">'+top.map(z=>kv(esc(z[0]),z[1]+' sold')).join('')+'</section>':''}<h2>Orders</h2><section class="ol">${l.map(ocard).join('')}</section>`;}
 if(t==='s'){const l=live.filter(o=>o.items.some(z=>z.sku===k)),q=l.reduce((a,o)=>a+o.items.filter(z=>z.sku===k).reduce((x,z)=>x+z.qty,0),0),S=data.sellers||{},st=(A(data.stock)||[]).find(z=>z.sku===k);
  const per=['week','month','quarter'].map(p=>{const r=A(S[p]);const n=r?r.findIndex(z=>z.sku===k):-1;return n>=0?kv({week:'Week',month:'Month',quarter:'90 days'}[p],'#'+(n+1)+(r[n].rev?' · '+inr(r[n].rev):'')):''}).join('');
  return `<section class="glass list">${kv('Sold today',q+' units')}${kv('Orders today',l.length)}${st?kv('In stock',st.onHand):''}${per}</section>${l.length?'<h2>Orders today</h2><section class="ol">'+l.map(ocard).join('')+'</section>':''}`;}
 if(t==='r'){const m={};live.forEach(o=>{(m[o.ch]=m[o.ch]||{n:0,amt:0});m[o.ch].n++;m[o.ch].amt+=o.amt});const by=Object.entries(m).sort((a,b)=>b[1].amt-a[1].amt),top=[...live].sort((a,b)=>b.amt-a.amt).slice(0,5);
  return `<section class="glass list">${kv('Revenue so far',inr(s.revenue))}${kv('Yesterday full day',inr(s.revenuePrev))}${kv('Order items',s.items)}${kv('Orders',orders.length)}</section><h2>By channel</h2><section class="glass list">${by.map(([c,v])=>`<div class="line" data-d="c:${esc(c)}"><span>${esc(c)}</span><b>${inr(v.amt)} · ${v.n}</b></div>`).join('')}</section><h2>Top orders</h2><section class="ol">${top.map(ocard).join('')}</section>`;}

 if(t==='rt'){const R=data.retail,S=R&&A(R.stores),x=S&&S.find(z=>String(z.name||'Store')===k);if(!x)return none('Store not in the latest data.');const n=v=>Number(v||0),tot=S.reduce((q,z)=>q+n(z.sales),0),B=A(x.billList);
  return `<section class="glass list">${kv('Sales (incl. GST)',inr(n(x.sales)))}${kv('Bills',n(x.bills))}${kv('Units',n(x.units))}${kv('Avg bill',inr(Math.round(n(x.sales)/Math.max(1,n(x.bills)))))}${kv('Units per bill',n(x.bills)?(n(x.units)/n(x.bills)).toFixed(1):'0')}${n(x.returns)?kv('Returns',n(x.returns)):''}${kv('Share of retail',(tot?Math.round(n(x.sales)/tot*100):0)+'%')}${R.at?kv('Updated',esc(R.at)):''}</section>${B?'<h2>Bills</h2><section class="glass list">'+B.map(z=>kv(esc(z.no||'Bill')+'<br><small>'+esc(z.time||'')+(z.units?' · '+z.units+' unit'+(z.units>1?'s':''):'')+'</small>',inr(n(z.amt)))).join('')+'</section>':'<p class="note" style="padding-bottom:6px">Bill-level detail is not in the latest data.</p>'}`;}
 if(t==='p'){const key=k.toLowerCase().replace(/[^a-z]/g,'');const norm=x=>String(x||'').toLowerCase().replace(/[^a-z]/g,'');
  const all=[...pend.map(x=>({...x})),...live.filter(o=>!pend.some(p=>String(p.id)===String(o.id)))];
  let l=all.filter(o=>/pending|unverified|label|pack|created|processing/i.test(o.status||'')&&o.status!=='Complete');
  if(/verif/.test(key))l=l.filter(o=>/verif/i.test(o.status));else if(/pack/.test(key))l=l.filter(o=>/pack|processing|created/i.test(o.status));else if(/label/.test(key))l=l.filter(o=>/label/i.test(o.status));else if(/fail/.test(key))l=all.filter(o=>/fail/i.test(o.status));
  l.sort((a,b)=>(b.ageH||0)-(a.ageH||0));
  return `<p class="note" style="padding-bottom:6px">${l.length} order${l.length===1?'':'s'} from the latest data. The dashboard count can be larger, as we only hold today's orders and the oldest pending ones.</p><section class="ol">${l.length?l.map(ocard).join(''):none('Nothing matching in the latest data.')}</section>`;}
 return none('Nothing to show.');}

function histView(s){const H=A(data.history);if(!H)return '';const iso=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
 let d=[...H].sort((a,b)=>a.d<b.d?-1:1).filter(x=>x.d<iso);d.push({d:iso,rev:s.revenue,items:s.items,orders:(data.orders||[]).length,partial:true,ch:(()=>{const m={};(data.orders||[]).filter(o=>o.status!=='Cancelled').forEach(o=>m[o.ch]=(m[o.ch]||0)+o.amt);return m})()});
 const N=hs,full=d.filter(x=>!x.partial),cur=full.slice(-N),prev=full.slice(-2*N,-N),tod=d[d.length-1],sum=(a,k)=>a.reduce((t,x)=>t+(x[k]||0),0),cr=sum(cur,'rev'),pr=sum(prev,'rev');
 const cc=[...cur,tod],mx=Math.max(1,...cc.map(x=>x.rev)),bw=300/cc.length,fmt=x=>{const t=new Date(x+'T00:00:00');return t.toLocaleDateString('en-IN',{day:'numeric',month:'short'})};
 const bars=cc.map((x,i)=>{const hh=Math.max(2,x.rev/mx*92);return `<rect x="${(i*bw+bw*.15+10).toFixed(1)}" y="${(100-hh).toFixed(1)}" width="${(bw*.7).toFixed(1)}" height="${hh.toFixed(1)}" rx="3" fill="url(#g)" opacity="${x.partial?.55:1}"/>`}).join('');
 const chs={};cur.forEach(x=>Object.entries(x.ch||{}).forEach(([k,v])=>{(chs[k]=chs[k]||{c:0,p:0}).c+=v}));prev.forEach(x=>Object.entries(x.ch||{}).forEach(([k,v])=>{(chs[k]=chs[k]||{c:0,p:0}).p+=v}));
 const chl=Object.entries(chs).sort((a,b)=>b[1].c-a[1].c);const ch=prev.length?pct(cr,pr):null;
 return `<h2>Revenue</h2><section class="glass list"><div class="pills" style="padding:4px 0 10px"><button data-h="7" class="${hs===7?'on':''}">7 days</button><button data-h="30" class="${hs===30?'on':''}">30 days</button></div>
 <div class="line" style="border:0"><span>${cur.length?(cur.length<N?'Last '+cur.length+' full days so far':'Last '+N+' full days'):'No full days yet'}</span><b>${inr(cr)}</b></div>
 <div class="line" style="border:0;padding-top:0"><span>${prev.length?'Previous '+prev.length+' days':'Previous period'}</span><b>${prev.length?inr(pr)+' <small>'+arrow(ch)+'</small>':'<small>no data yet</small>'}</b></div>
 <svg viewBox="0 0 320 118" style="width:100%;margin-top:6px"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#f1e2c0"/><stop offset="1" stop-color="#9c8358"/></linearGradient></defs><line x1="10" y1="100.5" x2="310" y2="100.5" stroke="rgba(231,211,168,.25)"/>${bars}<text x="10" y="114" font-size="9" fill="rgba(242,232,216,.55)">${fmt(cc[0].d)}</text><text x="310" y="114" font-size="9" text-anchor="end" fill="rgba(242,232,216,.55)">Today</text></svg>
 ${chl.length?'<div style="margin-top:8px">'+chl.map(([k,v])=>`<div class="line"><span>${esc(k)}</span><b>${inr(v.c)} <small>${v.p?arrow(pct(v.c,v.p)):''}</small></b></div>`).join('')+'</div>':''}</section><p class="note" style="padding-bottom:0">Totals use completed days. Today's bar (faded) is partial. History starts from when tracking began.</p>`;}
function retailView(){const R=data.retail;const S=R&&A(R.stores);if(!S)return `<section class="glass list"><div class="line"><span>Waiting for retail data</span><b><small>Logic ERP stores</small></b></div></section>`;
 const n=x=>Number(x||0),sum=k=>S.reduce((t,x)=>t+n(x[k]),0);const sales=sum('sales'),bills=sum('bills'),units=sum('units'),ret=sum('returns');
 const H=A(R.hourly);let hb='';if(H){const mx=Math.max(1,...H.map(x=>n(x.sales)));const w=300/H.length;hb=`<section class="glass" style="padding:16px 18px"><span class="eyebrow">Sales by hour</span><svg viewBox="0 0 320 100" style="width:100%;margin-top:8px"><defs><linearGradient id="rg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#f1e2c0"/><stop offset="1" stop-color="#9c8358"/></linearGradient></defs><line x1="10" y1="80.5" x2="310" y2="80.5" stroke="rgba(231,211,168,.25)"/>${H.map((x,i)=>{const bh=Math.max(1,n(x.sales)/mx*70);return `<rect x="${(10+i*w+w*.15).toFixed(1)}" y="${(80-bh).toFixed(1)}" width="${(w*.7).toFixed(1)}" height="${bh.toFixed(1)}" rx="2" fill="url(#rg)"/>`}).join('')}<text x="10" y="94" font-size="9" fill="rgba(242,232,216,.55)">${esc(H[0].h)}</text><text x="310" y="94" font-size="9" text-anchor="end" fill="rgba(242,232,216,.55)">${esc(H[H.length-1].h)}</text></svg></section>`;}
 return `<section class="glass hero"><span class="eyebrow">Retail sales today · incl. GST</span><div class="big">${inr(sales)}</div><div class="sub"><span class="chip">so far</span> Updated ${esc(R.at||'')}</div><div class="split"><div><b>${bills}</b><span>bills</span></div><div><b>${units}</b><span>units</span></div><div><b>${inr(Math.round(sales/Math.max(1,bills)))}</b><span>avg bill</span></div></div></section>
 ${ret?`<div class="grid2"><div class="glass tile amber"><b>${ret}</b><span>Returns today</span></div><div class="glass tile"><b>${units?(bills?(units/bills).toFixed(1):'0'):'0'}</b><span>Units per bill</span></div></div>`:''}
 <h2>Stores</h2>${S.slice().sort((a,b)=>n(b.sales)-n(a.sales)).map(x=>`<section class="glass list" data-d="rt:${esc(x.name||'Store')}"><div class="line" style="border:0"><span><b style="font-family:var(--serif,inherit)">${esc(x.name||'Store')}</b></span><b>${inr(n(x.sales))}</b></div><div class="line" style="border:0;padding-top:0"><span>${n(x.bills)} bills · ${n(x.units)} units</span><b><small>${n(x.returns)?n(x.returns)+(n(x.returns)===1?' return · ':' returns · '):''}${sales?Math.round(n(x.sales)/sales*100):0}% of retail</small></b></div></section>`).join('')}
 ${hb}<p class="note">Retail (Logic ERP) is kept separate from online. No customer details are shown.</p>`;}
function render(){if(!data){root.innerHTML=shell(`<header>${logo}<div><h1>Dressjet Ops</h1><p>${esc(status)}</p></div><button class="refresh" id="rf">Refresh</button></header>`);$('#rf').onclick=load;return;}
 const s=data.snapshot,orders=data.orders,live=orders.filter(o=>o.status!=='Cancelled');const pend=A(data.pending)||[];
 let h=`<header>${detail?'<button class="refresh" id="bk">‹ Back</button>':logo}<div><h1>${detail?detailTitle():({today:'Today',orders:'Orders',best:'Best sellers',stock:'Low stock',retail:'Retail'})[tab]}</h1><p>Dressjet · ${esc(s.at)}${status?' · '+esc(status):''}</p></div><button class="refresh" id="rf">Refresh</button></header><main>`;
 if(detail){h+=detailView(orders,live,pend,s);}
 else if(tab==='retail'){h+=retailView();}
 else if(tab==='today'){const m={};live.forEach(o=>{(m[o.ch]=m[o.ch]||{n:0,amt:0});m[o.ch].n++;m[o.ch].amt+=o.amt});const by=Object.entries(m).sort((a,b)=>b[1].amt-a[1].amt),max=Math.max(1,...by.map(c=>c[1].amt));
  h+=`<section class="glass hero" data-d="r:rev"><span class="eyebrow">Today's revenue</span><div class="big">${inr(s.revenue)}</div><div class="sub"><span class="chip">so far</span> Yesterday full day: ${inr(s.revenuePrev)}</div><div class="split"><div><b>${s.items}</b><span>order items</span></div><div><b>${orders.length}</b><span>orders</span></div><div><b>${inr(Math.round(s.revenue/Math.max(1,live.length)))}</b><span>avg order</span></div></div></section>
  ${histView(s)}
  <h2>Needs attention</h2><div class="grid2">${s.alerts.map(a=>`<div class="glass tile ${a.tone}" data-d="p:${esc(a.k)}"><b>${a.v}</b><span>${esc(a.k)}</span></div>`).join('')}</div>
  <h2>Channels today</h2><section class="glass list">${by.map(([c,v])=>`<div class="chrow" data-d="c:${esc(c)}"><div class="chtop"><span>${esc(c)}</span><span>${inr(v.amt)} · ${v.n}</span></div><div class="bar"><i style="width:${v.amt/max*100}%"></i></div></div>`).join('')}</section>
  <h2>Pending today</h2><section class="glass list">${s.pipeline.map(p=>`<div class="line" data-d="p:${esc(p.k)}"><span>${esc(p.k)}</span><b>${p.v}</b></div>`).join('')}</section>
${(()=>{let x='';
   const pd=A(data.pending);x+=`<h2>Pending dispatch${pd?' · '+pd.length:''}</h2>`+(pd?`<section class="ol">${[...pd].sort((a,b)=>b.ageH-a.ageH).slice(0,25).map(o=>`<article class="glass order" data-d="o:${esc(o.id)}"><div class="otop"><b>${esc(o.id)}</b><span class="st ${o.ageH>=48?'cancelled':o.ageH>=24?'pending_verification':'complete'}">${ageTxt(o.ageH)} old</span></div><div class="osku">${esc(o.skus||'')}</div><div class="ometa"><span>${esc(o.ch)} · ${esc(o.status)}</span><b>${o.amt?inr(o.amt):''}</b></div></article>`).join('')}</section>`:none('Waiting for dispatch data'));return x;})()}
  <h2>Catalog sync</h2><section class="glass list">${s.sync.map(p=>`<div class="line"><span>${esc(p.k)}</span><b>${p.v}</b></div>`).join('')}<div class="line"><span>Channel listings</span><b>${Number(s.listings).toLocaleString('en-IN')}</b></div></section>`;}
 else if(tab==='stock'){const st=A(data.stock);const wk=(data.sellers&&data.sellers.week)||[];const per={};wk.forEach(x=>{if(x.qty)per[x.sku]=x.qty/7});
  const rows=st?st.map(x=>{const pd=x.perDay!=null?x.perDay:(per[x.sku]||0);return {...x,pd,days:pd>0?x.onHand/pd:null}}).sort((a,b)=>(a.days===null)-(b.days===null)||(a.days!==null?a.days-b.days:a.onHand-b.onHand)):[];
  const T=data.stockTotals;h+=T?`<div class="grid2"><div class="glass tile"><b>${Number(T.units).toLocaleString('en-IN')}</b><span>Units in stock</span></div><div class="glass tile"><b>${Number(T.skus).toLocaleString('en-IN')}</b><span>SKUs</span></div></div><div class="glass tile ${T.oosPct>=25?'amber':''}" style="margin-top:12px"><b>${T.oosPct}%</b><span>Out of stock</span></div><h2>Fast sellers</h2>`:'';
  h+=st?`<section class="glass list">${rows.slice(0,25).map(x=>`<div class="line" data-d="s:${esc(x.sku)}"><span>${esc(x.sku)}<br><small>${x.pd>0?x.pd.toFixed(1)+'/day':'selling pace n/a'}</small></span><b class="${(x.days!==null?x.days<7:x.onHand<10)?'low':''}">${x.days!==null?(x.days<1?'<1':Math.round(x.days))+'d left · ':''}${x.onHand} in stock</b></div>`).join('')}</section><p class="note">Fast sellers. Lowest stock first${rows.some(x=>x.days!==null)?', by days left at recent pace':''}.</p>`:none('Waiting for stock data');} else if(tab==='best'){const t={};live.forEach(o=>o.items.forEach(i=>{const x=(t[i.sku]=t[i.sku]||{sku:i.sku,qty:0,orders:0});x.qty+=i.qty;x.orders++}));
  const S=data.sellers||{};const P=[['today','Today',Object.values(t).sort((a,b)=>b.qty-a.qty||b.orders-a.orders)],['week','Week',A(S.week)],['month','Month',A(S.month)],['quarter','90 days',A(S.quarter)]].filter(p=>p[2]||p[0]==='today');
  if(!P.find(p=>p[0]===bs))bs='today';const rows=P.find(p=>p[0]===bs)[2]||[];const val=r=>r.qty!=null?r.qty:(r.rev||0);const mx=Math.max(1,...rows.map(val));
  h+=`<div class="pills">${P.map(p=>`<button data-b="${p[0]}" class="${bs===p[0]?'on':''}">${p[1]}</button>`).join('')}</div><section class="glass list">${rows.length?rows.slice(0,15).map((r,n)=>`<div class="chrow" data-d="s:${esc(r.sku)}"><div class="chtop"><span>${n+1}. ${esc(r.sku)}</span><span>${r.qty!=null?r.qty+' sold':''}${r.qty!=null&&r.rev?' · ':''}${r.rev?inr(r.rev):''}</span></div><div class="bar"><i style="width:${val(r)/mx*100}%"></i></div></div>`).join(''):'<div class="empty">No sales yet.</div>'}</section><p class="note">${bs==='today'?'Units from today\'s non-cancelled orders.':'By revenue from the Sales dashboard.'}</p>`;}
 else{const chans=['All',...new Set(orders.map(o=>o.ch))];const list=orders.filter(o=>(ch==='All'||o.ch===ch)&&(!q||(o.id+o.items.map(i=>i.sku).join(' ')).toLowerCase().includes(q.toLowerCase())));
  h+=`<div class="glass search"><input id="q" placeholder="Search order or SKU" value="${esc(q)}"></div><div class="pills">${chans.map(c=>`<button data-c="${esc(c)}" class="${c===ch?'on':''}">${esc(c)}</button>`).join('')}</div><section class="ol">${list.length?list.map(o=>`<article class="glass order" data-d="o:${esc(o.id)}"><div class="otop"><b>${esc(o.id)}</b><span class="st ${o.status.toLowerCase()}">${esc(o.status)}</span></div><div class="osku">${o.items.map(i=>esc(i.sku)+(i.qty>1?' ×'+i.qty:'')).join(', ')}</div><div class="ometa"><span>${esc(o.ch)} · ${esc(o.pay)} · ${esc(o.time)}</span><b>${o.amt?inr(o.amt):'—'}</b></div></article>`).join(''):'<div class="glass empty">No orders match.</div>'}</section>`;}
 h+=`</main><nav class="glass tabbar"><button data-t="today" class="${tab==='today'?'on':''}">Today</button><button data-t="orders" class="${tab==='orders'?'on':''}">Orders</button><button data-t="best" class="${tab==='best'?'on':''}">Sellers</button><button data-t="stock" class="${tab==='stock'?'on':''}">Stock</button><button data-t="retail" class="${tab==='retail'?'on':''}">Retail</button></nav>`;
 root.innerHTML=shell(h);$('#rf').onclick=load;document.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{tab=b.dataset.t;detail=null;render()});document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{detail=b.dataset.d;window.scrollTo(0,0);render()});const bk=$('#bk');if(bk)bk.onclick=()=>{detail=null;render()};document.querySelectorAll('[data-h]').forEach(b=>b.onclick=()=>{hs=+b.dataset.h;render()});document.querySelectorAll('[data-b]').forEach(b=>b.onclick=()=>{bs=b.dataset.b;render()});document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{ch=b.dataset.c;render()});
 const qi=$('#q');if(qi)qi.oninput=e=>{q=e.target.value;const p=e.target.selectionStart;render();const n=$('#q');n.focus();n.setSelectionRange(p,p)};}
let timer;function start(){load();clearInterval(timer);timer=setInterval(()=>{if(!document.hidden)load()},((window.DJ_CONFIG||{}).pollMinutes||5)*60000);}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&priv)load()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
lockScreen();
