import {setup,unlock,decryptPayload,kid} from './crypto.js';
const $=s=>document.querySelector(s),root=$('#root');
const inr=n=>'₹'+Number(n).toLocaleString('en-IN');
const A=x=>Array.isArray(x)&&x.length?x:null;const pct=(a,b)=>b?Math.round((a-b)/b*100):null;const arrow=p=>p===null?'':(p>=0?'▲ ':'▼ ')+Math.abs(p)+'%';const ageTxt=h=>h<24?Math.round(h)+'h':Math.floor(h/24)+'d '+Math.round(h%24)+'h';const none=m=>`<div class="glass empty">${m}</div>`;
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const LS=localStorage;let bs='today',priv=null,myKid=null,data=null,tab='today',q='',ch='All',status='';
const shell=inner=>`<div class="app"><div class="blob b1"></div><div class="blob b2"></div><div class="blob b3"></div>${inner}</div>`;
const logo='<img class="logo" src="icon-192.png" alt="Dressjet">';
function lockScreen(){const v=JSON.parse(LS.getItem('dj_vault')||'null');
 root.innerHTML=shell(`<div class="lock">${logo}<h1>Dressjet Ops</h1>${v?`<p>Enter your passphrase to open.</p><div class="glass"><input id="pw" type="password" autocomplete="current-password" placeholder="Passphrase"><button class="btn" id="go">Unlock</button><div class="err" id="err"></div></div>`:
 `<p>First time on this phone. Choose a passphrase. It never leaves this phone and cannot be recovered, so keep it somewhere safe.</p><div class="glass"><input id="pw" type="password" placeholder="Passphrase (10+ characters)"><input id="pw2" type="password" placeholder="Repeat passphrase"><button class="btn" id="go">Create</button><div class="err" id="err"></div></div>`}</div>`);
 $('#go').onclick=async()=>{const e=$('#err');e.textContent='';const pw=$('#pw').value;
  try{ if(v){priv=await unlock(v,pw);myKid=await kid(v.pub);start();}
   else{ if(pw.length<10){e.textContent='Use at least 10 characters.';return;} if(pw!==$('#pw2').value){e.textContent='Passphrases do not match.';return;}
    $('#go').textContent='Working...';const r=await setup(pw);LS.setItem('dj_vault',JSON.stringify(r.vault));showKey(r.pubText);} }
  catch(x){e.textContent=v?'Wrong passphrase.':'Something went wrong: '+x.message;$('#go').textContent=v?'Unlock':'Create';}};}
function showKey(t){root.innerHTML=shell(`<div class="lock">${logo}<h1>Almost done</h1><p>Send this public key to your assistant. It is not secret. It lets updates be locked so only this phone can read them.</p><div class="glass"><div class="keybox" id="k">${esc(t)}</div><button class="btn" id="cp">Copy key</button><button class="btn alt" id="sh">Share key</button><button class="btn alt" id="nx">Continue</button></div></div>`);
 $('#cp').onclick=async()=>{try{await navigator.clipboard.writeText(t);$('#cp').textContent='Copied'}catch{}};
 $('#sh').onclick=()=>navigator.share?navigator.share({text:t}):0;$('#nx').onclick=lockScreen;}
async function fetchLatest(){const repo=(window.DJ_CONFIG||{}).repo;
 const r=await fetch(`https://api.github.com/repos/${repo}/issues/comments?sort=created&direction=desc&per_page=1&_=${Date.now()}`,{cache:'no-store',headers:{Accept:'application/vnd.github+json'}});
 if(!r.ok)throw new Error('GitHub '+r.status);const j=await r.json();if(!j.length)throw new Error('No data yet');
 const body=j[0].body.trim().replace(/^```(json)?/,'').replace(/```$/,'').trim();LS.setItem('dj_last',body);return body;}
async function load(){try{status='Updating...';render();let b;try{b=await fetchLatest();status='';}catch(e){b=LS.getItem('dj_last');status=b?'Offline, showing last saved data':'No data yet: '+e.message;if(!b){render();return;}}
 data=await decryptPayload(JSON.parse(b),priv,myKid);}catch(e){status='Could not read update: '+e.message;}render();}
function render(){if(!data){root.innerHTML=shell(`<header>${logo}<div><h1>Dressjet Ops</h1><p>${esc(status)}</p></div><button class="refresh" id="rf">Refresh</button></header>`);$('#rf').onclick=load;return;}
 const s=data.snapshot,orders=data.orders,live=orders.filter(o=>o.status!=='Cancelled');
 let h=`<header>${logo}<div><h1>${({today:'Today',orders:'Orders',best:'Best sellers',stock:'Low stock',ret:'Returns'})[tab]}</h1><p>Dressjet · ${esc(s.at)}${status?' · '+esc(status):''}</p></div><button class="refresh" id="rf">Refresh</button></header><main>`;
 if(tab==='today'){const m={};live.forEach(o=>{(m[o.ch]=m[o.ch]||{n:0,amt:0});m[o.ch].n++;m[o.ch].amt+=o.amt});const by=Object.entries(m).sort((a,b)=>b[1].amt-a[1].amt),max=Math.max(1,...by.map(c=>c[1].amt));
  h+=`<section class="glass hero"><span class="eyebrow">Today's revenue</span><div class="big">${inr(s.revenue)}</div><div class="sub"><span class="chip">so far</span> Yesterday full day: ${inr(s.revenuePrev)}</div><div class="split"><div><b>${s.items}</b><span>order items</span></div><div><b>${orders.length}</b><span>orders</span></div><div><b>${inr(Math.round(s.revenue/Math.max(1,live.length)))}</b><span>avg order</span></div></div></section>
  <h2>Needs attention</h2><div class="grid2">${s.alerts.map(a=>`<div class="glass tile ${a.tone}"><b>${a.v}</b><span>${esc(a.k)}</span></div>`).join('')}</div>
  <h2>Channels today</h2><section class="glass list">${by.map(([c,v])=>`<div class="chrow"><div class="chtop"><span>${esc(c)}</span><span>${inr(v.amt)} · ${v.n}</span></div><div class="bar"><i style="width:${v.amt/max*100}%"></i></div></div>`).join('')}</section>
  <h2>Pending today</h2><section class="glass list">${s.pipeline.map(p=>`<div class="line"><span>${esc(p.k)}</span><b>${p.v}</b></div>`).join('')}</section>
${(()=>{let x='';const c=data.compare;
   if(c&&c.lastWeekSameDay){const L=c.lastWeekSameDay,r=pct(s.revenue,L.rev),it=pct(s.items,L.items);x+=`<h2>Today vs same day last week</h2><section class="glass list"><div class="line"><span>Revenue</span><b>${inr(s.revenue)} <small>vs ${inr(L.rev)} ${arrow(r)}</small></b></div><div class="line"><span>Order items</span><b>${s.items} <small>vs ${L.items} ${arrow(it)}</small></b></div></section>`;}
   if(A(data.daily)){const d=data.daily,mx=Math.max(1,...d.map(z=>z.rev));x+=`<h2>Last ${d.length} days</h2><section class="glass list">${d.map(z=>`<div class="chrow"><div class="chtop"><span>${esc(z.d)}</span><span>${inr(z.rev)} · ${z.items}</span></div><div class="bar"><i style="width:${z.rev/mx*100}%"></i></div></div>`).join('')}</section>`;}
   if(A(data.channels7)){const d=data.channels7,mx=Math.max(1,...d.map(z=>z.rev));x+=`<h2>Channels · 7 days</h2><section class="glass list">${d.map(z=>`<div class="chrow"><div class="chtop"><span>${esc(z.ch)}</span><span>${inr(z.rev)} · ${z.orders}</span></div><div class="bar"><i style="width:${z.rev/mx*100}%"></i></div></div>`).join('')}</section>`;}
   const pd=A(data.pending);x+=`<h2>Pending dispatch${pd?' · '+pd.length:''}</h2>`+(pd?`<section class="ol">${[...pd].sort((a,b)=>b.ageH-a.ageH).slice(0,25).map(o=>`<article class="glass order"><div class="otop"><b>${esc(o.id)}</b><span class="st ${o.ageH>=48?'cancelled':o.ageH>=24?'pending_verification':'complete'}">${ageTxt(o.ageH)} old</span></div><div class="osku">${esc(o.skus||'')}</div><div class="ometa"><span>${esc(o.ch)} · ${esc(o.status)}</span><b>${o.amt?inr(o.amt):''}</b></div></article>`).join('')}</section>`:none('Waiting for dispatch data'));return x;})()}
  <h2>Catalog sync</h2><section class="glass list">${s.sync.map(p=>`<div class="line"><span>${esc(p.k)}</span><b>${p.v}</b></div>`).join('')}<div class="line"><span>Channel listings</span><b>${Number(s.listings).toLocaleString('en-IN')}</b></div></section>`;}
 else if(tab==='stock'){const st=A(data.stock);const wk=(data.sellers&&data.sellers.week)||[];const per={};wk.forEach(x=>per[x.sku]=x.qty/7);
  const rows=st?st.map(x=>({...x,pd:x.perDay!=null?x.perDay:(per[x.sku]||0)})).map(x=>({...x,days:x.pd>0?x.onHand/x.pd:null})).filter(x=>x.days!==null).sort((a,b)=>a.days-b.days):[];
  h+=st?(rows.length?`<section class="glass list">${rows.slice(0,25).map(x=>`<div class="line"><span>${esc(x.sku)}<br><small>${x.onHand} left · ${x.pd.toFixed(1)}/day</small></span><b class="${x.days<7?'low':''}">${x.days<1?'<1':Math.round(x.days)}d</b></div>`).join('')}</section><p class="note">Days of stock left at the last 7 days' selling pace. Fast sellers first.</p>`:none('No fast sellers with stock data.')):none('Waiting for stock data');}
 else if(tab==='ret'){const r=data.returns;
  h+=r?`<div class="grid2"><div class="glass tile amber"><b>${r.rto||0}</b><span>RTO / returned</span></div><div class="glass tile"><b>${r.customer||0}</b><span>Customer returns</span></div></div>${A(r.list)?`<section class="ol">${r.list.slice(0,30).map(o=>`<article class="glass order"><div class="otop"><b>${esc(o.id)}</b><span class="st cancelled">${esc(o.type||'Return')}</span></div><div class="osku">${esc(o.skus||'')}</div><div class="ometa"><span>${esc(o.ch||'')} · ${esc(o.date||'')}</span><b>${o.amt?inr(o.amt):''}</b></div></article>`).join('')}</section>`:none('No returns in this period.')}<p class="note">${esc(r.period||'Recent')}</p>`:none('Waiting for returns data');}
 else if(tab==='best'){const t={};live.forEach(o=>o.items.forEach(i=>{const x=(t[i.sku]=t[i.sku]||{sku:i.sku,qty:0,orders:0});x.qty+=i.qty;x.orders++}));
  const day=Object.values(t).sort((a,b)=>b.qty-a.qty||b.orders-a.orders);const wk=(data.sellers&&data.sellers.week)||null;
  const rows=(bs==='week'&&wk)?wk.map(x=>({sku:x.sku,qty:x.qty,orders:x.orders||0,rev:x.rev})):day;const mx=Math.max(1,...rows.map(r=>r.qty));
  h+=`<div class="pills"><button data-b="today" class="${bs==='today'?'on':''}">Today</button>${wk?`<button data-b="week" class="${bs==='week'?'on':''}">Last 7 days</button>`:''}</div><section class="glass list">${rows.length?rows.slice(0,15).map((r,n)=>`<div class="chrow"><div class="chtop"><span>${n+1}. ${esc(r.sku)}</span><span>${r.qty} sold${r.rev?' · '+inr(r.rev):''}</span></div><div class="bar"><i style="width:${r.qty/mx*100}%"></i></div></div>`).join(''):'<div class="empty">No sales yet.</div>'}</section>${bs==='today'?'<p class="note">Units from today\'s non-cancelled orders.</p>':'<p class="note">Units over the last 7 days.</p>'}`;}
 else{const chans=['All',...new Set(orders.map(o=>o.ch))];const list=orders.filter(o=>(ch==='All'||o.ch===ch)&&(!q||(o.id+o.items.map(i=>i.sku).join(' ')).toLowerCase().includes(q.toLowerCase())));
  h+=`<div class="glass search"><input id="q" placeholder="Search order or SKU" value="${esc(q)}"></div><div class="pills">${chans.map(c=>`<button data-c="${esc(c)}" class="${c===ch?'on':''}">${esc(c)}</button>`).join('')}</div><section class="ol">${list.length?list.map(o=>`<article class="glass order"><div class="otop"><b>${esc(o.id)}</b><span class="st ${o.status.toLowerCase()}">${esc(o.status)}</span></div><div class="osku">${o.items.map(i=>esc(i.sku)+(i.qty>1?' ×'+i.qty:'')).join(', ')}</div><div class="ometa"><span>${esc(o.ch)} · ${esc(o.pay)} · ${esc(o.time)}</span><b>${o.amt?inr(o.amt):'—'}</b></div></article>`).join(''):'<div class="glass empty">No orders match.</div>'}</section>`;}
 h+=`</main><nav class="glass tabbar"><button data-t="today" class="${tab==='today'?'on':''}">Today</button><button data-t="orders" class="${tab==='orders'?'on':''}">Orders</button><button data-t="best" class="${tab==='best'?'on':''}">Sellers</button><button data-t="stock" class="${tab==='stock'?'on':''}">Stock</button><button data-t="ret" class="${tab==='ret'?'on':''}">Returns</button></nav>`;
 root.innerHTML=shell(h);$('#rf').onclick=load;document.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{tab=b.dataset.t;render()});document.querySelectorAll('[data-b]').forEach(b=>b.onclick=()=>{bs=b.dataset.b;render()});document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{ch=b.dataset.c;render()});
 const qi=$('#q');if(qi)qi.oninput=e=>{q=e.target.value;const p=e.target.selectionStart;render();const n=$('#q');n.focus();n.setSelectionRange(p,p)};}
let timer;function start(){load();clearInterval(timer);timer=setInterval(()=>{if(!document.hidden)load()},((window.DJ_CONFIG||{}).pollMinutes||5)*60000);}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&priv)load()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
lockScreen();
