name: fix
on: workflow_dispatch
permissions:
  contents: write
jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          for f in [0-9]*-*; do git mv "$f" "$(echo "$f" | sed -E 's/^[0-9]+-//')"; done
          git config user.name bot
          git config user.email bot@users.noreply.github.com
          git commit -m "rename files"
          git push
